# IMPORTS

general install for using open ai models

In [336]:
import openai
from openai import OpenAI
import json
import io
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_distances

specific libraries for making images machine readable for chatgpt vision

In [337]:
from PIL import Image
from io import BytesIO
import base64
import re
import os
import csv

# CREDENTIALS AND AUTHENTICATIONS

In [ ]:
#client = OpenAI()

# FUNCTIONS

In [339]:
import os
import re
import shutil

# Define the directories
train_dir = '/home/salvador_cb/3_term/Applied_research_studio/data/img/train'
overlap_dir = os.path.join(train_dir, 'overlap')
elevation_dir = os.path.join(train_dir, 'elevation')
street_dir = os.path.join(train_dir, 'street')
elevation_2_dir = os.path.join(train_dir, 'elevation_2')
street_2_dir = os.path.join(train_dir, 'street_2')

# Create the new directories if they don't exist
os.makedirs(elevation_2_dir, exist_ok=True)
os.makedirs(street_2_dir, exist_ok=True)

# Get the list of files in the overlap directory
overlap_files = os.listdir(overlap_dir)

# Extract city names from overlap file names using regex
city_names = []
for filename in overlap_files:
    match = re.match(r'^(.*)_overlap\.png$', filename)
    if match:
        city_names.append(match.group(1))  # Extract the city name

# Copy files from elevation and street folders to the new directories
for city_name in city_names:
    # Define the file paths
    elevation_file = os.path.join(elevation_dir, f"{city_name}_elevation.png")
    street_file = os.path.join(street_dir, f"{city_name}_street_network.png")

    # Copy elevation file to elevation_2 if it exists
    if os.path.exists(elevation_file):
        shutil.copy(elevation_file, elevation_2_dir)

    # Copy street file to street_2 if it exists
    if os.path.exists(street_file):
        shutil.copy(street_file, street_2_dir)

# Verify the number of files in the new directories
elevation_2_files = os.listdir(elevation_2_dir)
street_2_files = os.listdir(street_2_dir)

print(f"Number of files in elevation_2: {len(elevation_2_files)}")
print(f"Number of files in street_2: {len(street_2_files)}")
print(f"Number of files in overlap: {len(overlap_files)}")

Number of files in elevation_2: 1365
Number of files in street_2: 1365
Number of files in overlap: 1365

Turning an image to its b64 encoding (-> sending it as text)

In [340]:
def image_to_base64(image):
    buffered = BytesIO()
    image.save(buffered, format="PNG")  # You can change the format to PNG or other types if needed
    img_str = base64.b64encode(buffered.getvalue()).decode('utf-8')
    return img_str

Function for chatgpt vision

In [341]:
def gpt_vision(vision_prompt, image_encoded):
  response = client.chat.completions.create(
      model="chatgpt-4o-latest",
      messages=[
          {
            "role": "user",
            "content": [
              {"type": "text", "text": vision_prompt},
              { "type": "image_url",
                "image_url": {
                  "url": "data:image/jpeg;base64,"+ image_encoded,
                },
              },
            ],
          },
        ],
        max_tokens=5000,
  )
  return response.choices[0].message.content

In [342]:
def gptVisionApp(prompt, image):
  # encode to b64
  image_encoded = image_to_base64(image)

  global gptVisionAppPromptTemplate
  final_prompt = gptVisionAppPromptTemplate + prompt

  res = gpt_vision(final_prompt,image_encoded)

  #optionally collect results in a list (defined in the cell below)
  #anwser_collection.append(res)
  return res

Regex functions

In [343]:
def city_name_regex(img_path):
    match = re.search(r'/home/salvador_cb/3_term/Applied_research_studio/data/img/train/overlap/(.*)_overlap\.png', img_path)
    if match:
        city_country = match.group(1)
        # Split the city and country by the last comma
        parts = city_country.rsplit(", ", 1)
        if len(parts) == 2:
            city, country = parts
            return city.strip(), country.strip()
    # Return None for both city and country if the regex does not match
    return None, None

In [344]:
def tags_regex(description):
    match = re.search(r"\[(.*?)\]", description)
    if match:
        tags_list = match.group(1).replace('"', '').split(',')
        return tags_list
    return []

In [345]:
def desc_regex(img_desc):
    return re.sub(r'\[.*?\]', '', img_desc).strip()

# MAIN

In [362]:
csv_path = '/home/salvador_cb/3_term/Applied_research_studio/data/csv/overlap_metadata.csv'
if os.path.exists(csv_path):
    overlap_df = pd.read_csv(csv_path)
else:
    overlap_df = pd.DataFrame(columns=["country", "city", "overlap_file_name", "overlap_description", "overlap_tags"])

processed_cities = list(overlap_df['overlap_file_name'])

folder_path = '/home/salvador_cb/3_term/Applied_research_studio/data/img/train/overlap'

city_counter = 0
# Loop through all the files in the folder
for filename in os.listdir(folder_path):
    if filename.endswith('.png'):  # Assuming all your images are in PNG format
        # Construct the full file path
        file_path = os.path.join(folder_path, filename)
        city, country = city_name_regex(file_path)
        city_counter += 1
        print(f"Processing {city_counter} of {len(os.listdir(folder_path))} images: {filename}")

        if filename in processed_cities:
            print(f"{filename} is already processed. Skipping...")
            continue
        
        print(f'city: {city}, country: {country}')
        image_vis = Image.open(file_path)
        base64_image = image_to_base64(image_vis)
        
        # Use regex to extract the city and country names from the filename
        global gptVisionAppPromptTemplate
        gptVisionAppPromptTemplate = f"Here is a street layout map of the city {city}, {country}. give me a description and tags of the urban characteristics."

        img_desc = gpt_vision(f"""You are a model with advanced vision capabilities.
            Your task is to analyze the provided image and generate a detailed description of its features. The image shows an overlay of an urban street network on a grayscale topographic map of {city}, {country}. In this image, red lines represent streets and pathways, while the grayscale background illustrates the terrain, where lighter areas indicate higher elevations and darker areas indicate lower regions.
            Provide a comprehensive description of how the urban street network interacts with the underlying topography. Highlight how the street layout adapts to the terrain's features. For example, describe if a grid structure is situated in a valley, if roads curve to navigate around mountain ridges, if dense intersections are located near flat areas, or if arterial roads traverse elevated regions. Use specific observations to explain this interaction, such as noting a dense grid pattern in flat, low-elevation zones or winding roads along steep, elevated contours.
            Start with a general overview of how the urban network integrates with the natural landscape, then provide detail on specific areas of interest. Avoid using proper names or landmarks; focus solely on the physical characteristics and spatial relationships between the urban elements and the terrain. The description must be at least 200 characters.

            Additionally, return a Python list with exactly 10 tags or keywords that summarize the observed urban and topographic features. The format should be: ["tag1", "tag2", "tag3", "tag4", "tag5", "tag6", "tag7", "tag8", "tag9", "tag10"]. Use only descriptive terms relevant to the image, such as valley, mountain, grid, branching, winding, elevation, intersection, hillside, and contour.
            Do not include any markdown elements in your response, just the one body description and the list of tags.
            Example Output:
            "The image depicts a dense urban street network concentrated in a central valley, surrounded by elevated terrain. The streets in the valley form a grid-like pattern, while roads on the outskirts curve and meander to adapt to the hilly topography. A prominent arterial road cuts through the valley, connecting the central grid to the surrounding areas. The elevated regions feature sparse, winding roads that follow the contours of the terrain, with intersections primarily located at flatter areas near the valley edges. The overall layout demonstrates a clear adaptation of the urban network to the natural landscape, with dense development in the lowlands and sparse connectivity in the highlands."
            ["valley", "grid", "elevation", "winding", "intersection", "arterial road", "hillside", "contour", "dense", "sparse"]
            """, base64_image)
        tags = tags_regex(img_desc)
        tags_str = ','.join(tags)
        desc = desc_regex(img_desc)
        
        new_row = {'country': country, 'city': city, 'overlap_file_name': filename, 'overlap_description': desc, 'overlap_tags': tags_str}
        overlap_df = pd.concat([overlap_df, pd.DataFrame([new_row])], ignore_index=True)

Processing 1 of 1365 images: Xiamen, China_overlap.png
Xiamen, China_overlap.png is already processed. Skipping...
Processing 2 of 1365 images: Drammen, Norway_overlap.png
Drammen, Norway_overlap.png is already processed. Skipping...
Processing 3 of 1365 images: Reggio Emilia, Italy_overlap.png
Reggio Emilia, Italy_overlap.png is already processed. Skipping...
Processing 4 of 1365 images: Cologne, Germany_overlap.png
Cologne, Germany_overlap.png is already processed. Skipping...
Processing 5 of 1365 images: Yaounde, Cameroon_overlap.png
Yaounde, Cameroon_overlap.png is already processed. Skipping...
Processing 6 of 1365 images: Punta del Este, Uruguay_overlap.png
Punta del Este, Uruguay_overlap.png is already processed. Skipping...
Processing 7 of 1365 images: Constantine, Algeria_overlap.png
Constantine, Algeria_overlap.png is already processed. Skipping...
Processing 8 of 1365 images: Santiago de Chile, Chile_overlap.png
Santiago de Chile, Chile_overlap.png is already processed. Skipping...
Processing 9 of 1365 images: Franceville, Gabon_overlap.png
Franceville, Gabon_overlap.png is already processed. Skipping...
Processing 10 of 1365 images: Lobatse, Botswana_overlap.png
Lobatse, Botswana_overlap.png is already processed. Skipping...
Processing 11 of 1365 images: Pinsk, Belarus_overlap.png
Pinsk, Belarus_overlap.png is already processed. Skipping...
Processing 12 of 1365 images: Musanze, Rwanda_overlap.png
Musanze, Rwanda_overlap.png is already processed. Skipping...
Processing 13 of 1365 images: Brussels, Belgium_overlap.png
Brussels, Belgium_overlap.png is already processed. Skipping...
Processing 14 of 1365 images: Bizerte, Tunisia_overlap.png
Bizerte, Tunisia_overlap.png is already processed. Skipping...
Processing 15 of 1365 images: Kampot, Cambodia_overlap.png
Kampot, Cambodia_overlap.png is already processed. Skipping...
Processing 16 of 1365 images: Oyem, Gabon_overlap.png
Oyem, Gabon_overlap.png is already processed. Skipping...
Processing 17 of 1365 images: Mabaruma, Guyana_overlap.png
Mabaruma, Guyana_overlap.png is already processed. Skipping...
Processing 18 of 1365 images: Janakpur, Nepal_overlap.png
Janakpur, Nepal_overlap.png is already processed. Skipping...
Processing 19 of 1365 images: Fada N'gourma, Burkina Faso_overlap.png
Fada N'gourma, Burkina Faso_overlap.png is already processed. Skipping...
Processing 20 of 1365 images: Paphos, Cyprus_overlap.png
Paphos, Cyprus_overlap.png is already processed. Skipping...
Processing 21 of 1365 images: Beirut, Lebanon_overlap.png
Beirut, Lebanon_overlap.png is already processed. Skipping...
Processing 22 of 1365 images: Koper, Slovenia_overlap.png
Koper, Slovenia_overlap.png is already processed. Skipping...
Processing 23 of 1365 images: Dornbirn, Austria_overlap.png
Dornbirn, Austria_overlap.png is already processed. Skipping...
Processing 24 of 1365 images: Osaka, Japan_overlap.png
Osaka, Japan_overlap.png is already processed. Skipping...
Processing 25 of 1365 images: Kolding, Denmark_overlap.png
Kolding, Denmark_overlap.png is already processed. Skipping...
Processing 26 of 1365 images: Khujand, Tajikistan_overlap.png
Khujand, Tajikistan_overlap.png is already processed. Skipping...
Processing 27 of 1365 images: Rivas, Nicaragua_overlap.png
Rivas, Nicaragua_overlap.png is already processed. Skipping...
Processing 28 of 1365 images: Talca, Chile_overlap.png
Talca, Chile_overlap.png is already processed. Skipping...
Processing 29 of 1365 images: Brazzaville, Republic of the Congo_overlap.png
Brazzaville, Republic of the Congo_overlap.png is already processed. Skipping...
Processing 30 of 1365 images: Zurich, Switzerland_overlap.png
Zurich, Switzerland_overlap.png is already processed. Skipping...
Processing 31 of 1365 images: Rennes, France_overlap.png
Rennes, France_overlap.png is already processed. Skipping...
Processing 32 of 1365 images: Hyderabad, India_overlap.png
Hyderabad, India_overlap.png is already processed. Skipping...
Processing 33 of 1365 images: Ludhiana, India_overlap.png
Ludhiana, India_overlap.png is already processed. Skipping...
Processing 34 of 1365 images: Zanzibar City, Tanzania_overlap.png
Zanzibar City, Tanzania_overlap.png is already processed. Skipping...
Processing 35 of 1365 images: Gliwice, Poland_overlap.png
Gliwice, Poland_overlap.png is already processed. Skipping...
Processing 36 of 1365 images: Narva, Estonia_overlap.png
Narva, Estonia_overlap.png is already processed. Skipping...
Processing 37 of 1365 images: Christchurch, New Zealand_overlap.png
Christchurch, New Zealand_overlap.png is already processed. Skipping...
Processing 38 of 1365 images: Nova Gorica, Slovenia_overlap.png
Nova Gorica, Slovenia_overlap.png is already processed. Skipping...
Processing 39 of 1365 images: Parakou, Benin_overlap.png
Parakou, Benin_overlap.png is already processed. Skipping...
Processing 40 of 1365 images: Cluj-Napoca, Romania_overlap.png
Cluj-Napoca, Romania_overlap.png is already processed. Skipping...
Processing 41 of 1365 images: Geelong, Australia_overlap.png
Geelong, Australia_overlap.png is already processed. Skipping...
Processing 42 of 1365 images: Suva, Fiji_overlap.png
Suva, Fiji_overlap.png is already processed. Skipping...
Processing 43 of 1365 images: Mecca, Saudi Arabia_overlap.png
Mecca, Saudi Arabia_overlap.png is already processed. Skipping...
Processing 44 of 1365 images: Dapaong, Togo_overlap.png
Dapaong, Togo_overlap.png is already processed. Skipping...
Processing 45 of 1365 images: Liège, Belgium_overlap.png
Liège, Belgium_overlap.png is already processed. Skipping...
Processing 46 of 1365 images: Butare, Rwanda_overlap.png
Butare, Rwanda_overlap.png is already processed. Skipping...
Processing 47 of 1365 images: Touba, Senegal_overlap.png
Touba, Senegal_overlap.png is already processed. Skipping...
Processing 48 of 1365 images: Kavala, Greece_overlap.png
Kavala, Greece_overlap.png is already processed. Skipping...
Processing 49 of 1365 images: Luganville, Vanuatu_overlap.png
Luganville, Vanuatu_overlap.png is already processed. Skipping...
Processing 50 of 1365 images: Pleven, Bulgaria_overlap.png
Pleven, Bulgaria_overlap.png is already processed. Skipping...
Processing 51 of 1365 images: Amsterdam, Netherlands_overlap.png
Amsterdam, Netherlands_overlap.png is already processed. Skipping...
Processing 52 of 1365 images: Schaffhausen, Switzerland_overlap.png
Schaffhausen, Switzerland_overlap.png is already processed. Skipping...
Processing 53 of 1365 images: Golfito, Costa Rica_overlap.png
Golfito, Costa Rica_overlap.png is already processed. Skipping...
Processing 54 of 1365 images: Onitsha, Nigeria_overlap.png
Onitsha, Nigeria_overlap.png is already processed. Skipping...
Processing 55 of 1365 images: Köniz, Switzerland_overlap.png
Köniz, Switzerland_overlap.png is already processed. Skipping...
Processing 56 of 1365 images: Changwon, South Korea_overlap.png
Changwon, South Korea_overlap.png is already processed. Skipping...
Processing 57 of 1365 images: Lund, Sweden_overlap.png
Lund, Sweden_overlap.png is already processed. Skipping...
Processing 58 of 1365 images: Rijeka, Croatia_overlap.png
Rijeka, Croatia_overlap.png is already processed. Skipping...
Processing 59 of 1365 images: Pasig, Philippines_overlap.png
Pasig, Philippines_overlap.png is already processed. Skipping...
Processing 60 of 1365 images: Andijan, Uzbekistan_overlap.png
Andijan, Uzbekistan_overlap.png is already processed. Skipping...
Processing 61 of 1365 images: Nhlangano, Eswatini_overlap.png
Nhlangano, Eswatini_overlap.png is already processed. Skipping...
Processing 62 of 1365 images: Adana, Turkey_overlap.png
Adana, Turkey_overlap.png is already processed. Skipping...
Processing 63 of 1365 images: San Miguel de Tucumán, Argentina_overlap.png
San Miguel de Tucumán, Argentina_overlap.png is already processed. Skipping...
Processing 64 of 1365 images: Bordeaux, France_overlap.png
Bordeaux, France_overlap.png is already processed. Skipping...
Processing 65 of 1365 images: Larnaca, Cyprus_overlap.png
Larnaca, Cyprus_overlap.png is already processed. Skipping...
Processing 66 of 1365 images: Lalitpur, Nepal_overlap.png
Lalitpur, Nepal_overlap.png is already processed. Skipping...
Processing 67 of 1365 images: Limerick, Ireland_overlap.png
Limerick, Ireland_overlap.png is already processed. Skipping...
Processing 68 of 1365 images: Libreville, Gabon_overlap.png
Libreville, Gabon_overlap.png is already processed. Skipping...
Processing 69 of 1365 images: Rome, Italy_overlap.png
Rome, Italy_overlap.png is already processed. Skipping...
Processing 70 of 1365 images: La Louvière, Belgium_overlap.png
La Louvière, Belgium_overlap.png is already processed. Skipping...
Processing 71 of 1365 images: Malang, Indonesia_overlap.png
Malang, Indonesia_overlap.png is already processed. Skipping...
Processing 72 of 1365 images: Bucharest, Romania_overlap.png
Bucharest, Romania_overlap.png is already processed. Skipping...
Processing 73 of 1365 images: Rishon LeZion, Israel_overlap.png
Rishon LeZion, Israel_overlap.png is already processed. Skipping...
Processing 74 of 1365 images: Pedro Juan Caballero, Paraguay_overlap.png
Pedro Juan Caballero, Paraguay_overlap.png is already processed. Skipping...
Processing 75 of 1365 images: La Chorrera, Panama_overlap.png
La Chorrera, Panama_overlap.png is already processed. Skipping...
Processing 76 of 1365 images: Bologna, Italy_overlap.png
Bologna, Italy_overlap.png is already processed. Skipping...
Processing 77 of 1365 images: Kenema, Sierra Leone_overlap.png
Kenema, Sierra Leone_overlap.png is already processed. Skipping...
Processing 78 of 1365 images: Busan, South Korea_overlap.png
Busan, South Korea_overlap.png is already processed. Skipping...
Processing 79 of 1365 images: Hamilton, New Zealand_overlap.png
Hamilton, New Zealand_overlap.png is already processed. Skipping...
Processing 80 of 1365 images: Philadelphia, USA_overlap.png
Philadelphia, USA_overlap.png is already processed. Skipping...
Processing 81 of 1365 images: Hrodna, Belarus_overlap.png
Hrodna, Belarus_overlap.png is already processed. Skipping...
Processing 82 of 1365 images: Petah Tikva, Israel_overlap.png
Petah Tikva, Israel_overlap.png is already processed. Skipping...
Processing 83 of 1365 images: El Obeid, Sudan_overlap.png
El Obeid, Sudan_overlap.png is already processed. Skipping...
Processing 84 of 1365 images: Odessa, Ukraine_overlap.png
Odessa, Ukraine_overlap.png is already processed. Skipping...
Processing 85 of 1365 images: Muharraq, Bahrain_overlap.png
Muharraq, Bahrain_overlap.png is already processed. Skipping...
Processing 86 of 1365 images: Medan, Indonesia_overlap.png
Medan, Indonesia_overlap.png is already processed. Skipping...
Processing 87 of 1365 images: Hlotse, Lesotho_overlap.png
Hlotse, Lesotho_overlap.png is already processed. Skipping...
Processing 88 of 1365 images: Marijampole, Lithuania_overlap.png
Marijampole, Lithuania_overlap.png is already processed. Skipping...
Processing 89 of 1365 images: Maiduguri, Nigeria_overlap.png
Maiduguri, Nigeria_overlap.png is already processed. Skipping...
Processing 90 of 1365 images: Famagusta, Cyprus_overlap.png
Famagusta, Cyprus_overlap.png is already processed. Skipping...
Processing 91 of 1365 images: Telavi, Georgia_overlap.png
Telavi, Georgia_overlap.png is already processed. Skipping...
Processing 92 of 1365 images: Ahmedabad, India_overlap.png
Ahmedabad, India_overlap.png is already processed. Skipping...
Processing 93 of 1365 images: Plzen, Czech Republic_overlap.png
Plzen, Czech Republic_overlap.png is already processed. Skipping...
Processing 94 of 1365 images: Bimbo, Central African Republic_overlap.png
Bimbo, Central African Republic_overlap.png is already processed. Skipping...
Processing 95 of 1365 images: Coimbra, Portugal_overlap.png
Coimbra, Portugal_overlap.png is already processed. Skipping...
Processing 96 of 1365 images: Copenhagen, Denmark_overlap.png
Copenhagen, Denmark_overlap.png is already processed. Skipping...
Processing 97 of 1365 images: Nagoya, Japan_overlap.png
Nagoya, Japan_overlap.png is already processed. Skipping...
Processing 98 of 1365 images: Nukus, Uzbekistan_overlap.png
Nukus, Uzbekistan_overlap.png is already processed. Skipping...
Processing 99 of 1365 images: Jimma, Ethiopia_overlap.png
Jimma, Ethiopia_overlap.png is already processed. Skipping...
Processing 100 of 1365 images: Kandahar, Afghanistan_overlap.png
Kandahar, Afghanistan_overlap.png is already processed. Skipping...
Processing 101 of 1365 images: Ngerulmud, Palau_overlap.png
Ngerulmud, Palau_overlap.png is already processed. Skipping...
Processing 102 of 1365 images: Dubrovnik, Croatia_overlap.png
Dubrovnik, Croatia_overlap.png is already processed. Skipping...
Processing 103 of 1365 images: Foshan, China_overlap.png
Foshan, China_overlap.png is already processed. Skipping...
Processing 104 of 1365 images: Takeo, Cambodia_overlap.png
Takeo, Cambodia_overlap.png is already processed. Skipping...
Processing 105 of 1365 images: Pokhara, Nepal_overlap.png
Pokhara, Nepal_overlap.png is already processed. Skipping...
Processing 106 of 1365 images: Taguig, Philippines_overlap.png
Taguig, Philippines_overlap.png is already processed. Skipping...
Processing 107 of 1365 images: Goiânia, Brazil_overlap.png
Goiânia, Brazil_overlap.png is already processed. Skipping...
Processing 108 of 1365 images: Lyon, France_overlap.png
Lyon, France_overlap.png is already processed. Skipping...
Processing 109 of 1365 images: Villavicencio, Colombia_overlap.png
Villavicencio, Colombia_overlap.png is already processed. Skipping...
Processing 110 of 1365 images: Braila, Romania_overlap.png
Braila, Romania_overlap.png is already processed. Skipping...
Processing 111 of 1365 images: Jonava, Lithuania_overlap.png
Jonava, Lithuania_overlap.png is already processed. Skipping...
Processing 112 of 1365 images: Gizo, Solomon Islands_overlap.png
Gizo, Solomon Islands_overlap.png is already processed. Skipping...
Processing 113 of 1365 images: Rezekne, Latvia_overlap.png
Rezekne, Latvia_overlap.png is already processed. Skipping...
Processing 114 of 1365 images: Huambo, Angola_overlap.png
Huambo, Angola_overlap.png is already processed. Skipping...
Processing 115 of 1365 images: Tripoli, Lebanon_overlap.png
Tripoli, Lebanon_overlap.png is already processed. Skipping...
Processing 116 of 1365 images: Paris, France_overlap.png
Paris, France_overlap.png is already processed. Skipping...
Processing 117 of 1365 images: Bo, Sierra Leone_overlap.png
Bo, Sierra Leone_overlap.png is already processed. Skipping...
Processing 118 of 1365 images: Luque, Paraguay_overlap.png
Luque, Paraguay_overlap.png is already processed. Skipping...
Processing 119 of 1365 images: Cartago, Costa Rica_overlap.png
Cartago, Costa Rica_overlap.png is already processed. Skipping...
Processing 120 of 1365 images: Belmopan, Belize_overlap.png
Belmopan, Belize_overlap.png is already processed. Skipping...
Processing 121 of 1365 images: Fomboni, Comoros_overlap.png
Fomboni, Comoros_overlap.png is already processed. Skipping...
Processing 122 of 1365 images: Keren, Eritrea_overlap.png
Keren, Eritrea_overlap.png is already processed. Skipping...
Processing 123 of 1365 images: Kakata, Liberia_overlap.png
Kakata, Liberia_overlap.png is already processed. Skipping...
Processing 124 of 1365 images: Agadez, Niger_overlap.png
Agadez, Niger_overlap.png is already processed. Skipping...
Processing 125 of 1365 images: Keelung, Taiwan_overlap.png
Keelung, Taiwan_overlap.png is already processed. Skipping...
Processing 126 of 1365 images: Rasht, Iran_overlap.png
Rasht, Iran_overlap.png is already processed. Skipping...
Processing 127 of 1365 images: Charlotte, USA_overlap.png
Charlotte, USA_overlap.png is already processed. Skipping...
Processing 128 of 1365 images: Cali, Colombia_overlap.png
Cali, Colombia_overlap.png is already processed. Skipping...
Processing 129 of 1365 images: Islamabad, Pakistan_overlap.png
Islamabad, Pakistan_overlap.png is already processed. Skipping...
Processing 130 of 1365 images: Douala, Cameroon_overlap.png
Douala, Cameroon_overlap.png is already processed. Skipping...
Processing 131 of 1365 images: Abidjan, Ivory Coast_overlap.png
Abidjan, Ivory Coast_overlap.png is already processed. Skipping...
Processing 132 of 1365 images: Nakhchivan, Azerbaijan_overlap.png
Nakhchivan, Azerbaijan_overlap.png is already processed. Skipping...
Processing 133 of 1365 images: Ioannina, Greece_overlap.png
Ioannina, Greece_overlap.png is already processed. Skipping...
Processing 134 of 1365 images: Kuwait City, Kuwait_overlap.png
Kuwait City, Kuwait_overlap.png is already processed. Skipping...
Processing 135 of 1365 images: Gwangju, South Korea_overlap.png
Gwangju, South Korea_overlap.png is already processed. Skipping...
Processing 136 of 1365 images: Nizwa, Oman_overlap.png
Nizwa, Oman_overlap.png is already processed. Skipping...
Processing 137 of 1365 images: Matadi, Democratic Republic of the Congo_overlap.png
Matadi, Democratic Republic of the Congo_overlap.png is already processed. Skipping...
Processing 138 of 1365 images: Bosaso, Somalia_overlap.png
Bosaso, Somalia_overlap.png is already processed. Skipping...
Processing 139 of 1365 images: Nicoya, Costa Rica_overlap.png
Nicoya, Costa Rica_overlap.png is already processed. Skipping...
Processing 140 of 1365 images: Basseterre, Saint Kitts and Nevis_overlap.png
Basseterre, Saint Kitts and Nevis_overlap.png is already processed. Skipping...
Processing 141 of 1365 images: Serdar, Turkmenistan_overlap.png
Serdar, Turkmenistan_overlap.png is already processed. Skipping...
Processing 142 of 1365 images: Bray, Ireland_overlap.png
Bray, Ireland_overlap.png is already processed. Skipping...
Processing 143 of 1365 images: Minsk, Belarus_overlap.png
Minsk, Belarus_overlap.png is already processed. Skipping...
Processing 144 of 1365 images: Ciudad Juarez, Mexico_overlap.png
Ciudad Juarez, Mexico_overlap.png is already processed. Skipping...
Processing 145 of 1365 images: Drogheda, Ireland_overlap.png
Drogheda, Ireland_overlap.png is already processed. Skipping...
Processing 146 of 1365 images: Columbus, United States_overlap.png
Columbus, United States_overlap.png is already processed. Skipping...
Processing 147 of 1365 images: Bossangoa, Central African Republic_overlap.png
Bossangoa, Central African Republic_overlap.png is already processed. Skipping...
Processing 148 of 1365 images: Karlstad, Sweden_overlap.png
Karlstad, Sweden_overlap.png is already processed. Skipping...
Processing 149 of 1365 images: Suwon, South Korea_overlap.png
Suwon, South Korea_overlap.png is already processed. Skipping...
Processing 150 of 1365 images: San Miguel, El Salvador_overlap.png
San Miguel, El Salvador_overlap.png is already processed. Skipping...
Processing 151 of 1365 images: Lome, Togo_overlap.png
Lome, Togo_overlap.png is already processed. Skipping...
Processing 152 of 1365 images: Ngaoundere, Cameroon_overlap.png
Ngaoundere, Cameroon_overlap.png is already processed. Skipping...
Processing 153 of 1365 images: Lublin, Poland_overlap.png
Lublin, Poland_overlap.png is already processed. Skipping...
Processing 154 of 1365 images: Perth, Australia_overlap.png
Perth, Australia_overlap.png is already processed. Skipping...
Processing 155 of 1365 images: Wau, South Sudan_overlap.png
Wau, South Sudan_overlap.png is already processed. Skipping...
Processing 156 of 1365 images: Usti nad Labem, Czech Republic_overlap.png
Usti nad Labem, Czech Republic_overlap.png is already processed. Skipping...
Processing 157 of 1365 images: Shiraz, Iran_overlap.png
Shiraz, Iran_overlap.png is already processed. Skipping...
Processing 158 of 1365 images: Arica, Chile_overlap.png
Arica, Chile_overlap.png is already processed. Skipping...
Processing 159 of 1365 images: Abéché, Chad_overlap.png
Abéché, Chad_overlap.png is already processed. Skipping...
Processing 160 of 1365 images: Kaolack, Senegal_overlap.png

In [363]:
overlap_df

,country,city,overlap_file_name,overlap_description,overlap_tags
0,China,Xiamen,"Xiamen, China_overlap.png",The image depicts an urban street network that...,"valley, grid, elevation, winding, intersection..."
1,Norway,Drammen,"Drammen, Norway_overlap.png",The image depicts a well-defined urban street ...,"valley, grid, elevation, winding, intersection..."
2,Italy,Reggio Emilia,"Reggio Emilia, Italy_overlap.png",The image illustrates a striking contrast betw...,"valley, grid, elevation, winding, intersection..."
3,Germany,Cologne,"Cologne, Germany_overlap.png",The image shows an urban street network densel...,"valley, grid, elevation, winding, intersection..."
4,Cameroon,Yaounde,"Yaounde, Cameroon_overlap.png",The image shows a densely woven urban street n...,"valley, grid, elevation, winding, intersection..."
...,...,...,...,...,...
1360,South Korea,Ulsan,"Ulsan, South Korea_overlap.png",The image illustrates an urban street network ...,"valley, grid, elevation, winding, intersection..."
1361,Ireland,Kilkenny,"Kilkenny, Ireland_overlap.png",The image depicts an urban street network over...,"valley, grid, elevation, winding, intersection..."
1362,Austria,Wels,"Wels, Austria_overlap.png",The image shows a dense urban street network p...,"valley, grid, elevation, winding, intersection..."
1363,Hong Kong,Sha Tin,"Sha Tin, Hong Kong_overlap.png",The image displays an urban street network lay...,"valley, grid, elevation, winding, intersection..."
1364,Romania,Constanta,"Constanta, Romania_overlap.png",The image shows a well-developed urban street ...,"valley, grid, elevation, winding, intersection..."

In [364]:
overlap_df.to_csv('/home/salvador_cb/3_term/Applied_research_studio/data/csv/overlap_metadata.csv', index=False, quoting=csv.QUOTE_ALL)

# streets

In [294]:
csv_path = '/home/salvador_cb/3_term/Applied_research_studio/data/csv/street_metadata.csv'
if os.path.exists(csv_path):
    street_df = pd.read_csv(csv_path)
else:
    street_df = pd.DataFrame(columns=["country", "city", "street_file_name", "street_description", "street_tags"])

processed_cities = list(street_df['street_file_name'])

folder_path = '/home/salvador_cb/3_term/Applied_research_studio/data/img/train/street_2'

city_counter = 0
# Loop through all the files in the folder
for filename in os.listdir(folder_path):
    if filename.endswith('.png'):  # Assuming all your images are in PNG format
        # Construct the full file path
        file_path = os.path.join(folder_path, filename)
        city, country = city_name_regex(file_path)
        city_counter += 1
        print(f"Processing {city_counter} of {len(os.listdir(folder_path))} images: {filename}")

        if filename in processed_cities:
            print(f"{filename} is already processed. Skipping...")
            continue
        
        print(f'city: {city}, country: {country}')
        image_vis = Image.open(file_path)
        base64_image = image_to_base64(image_vis)
        
        # Use regex to extract the city and country names from the filename
        global gptVisionAppPromptTemplate
        gptVisionAppPromptTemplate = f"Here is a street layout map of the city {city}, {country}. give me a description and tags of the urban characteristics."

        img_desc = gpt_vision(f"""You are a model with vision capabilities.
            Your task is to generate a description of the images.
            Each image shows the street network of {city}, {country}.
            The streets are represented as red lines on a white background. The density, layout, and structure of the streets vary across the image.
            Return a text description of the image, describing the urban features of the street network. Focus on aspects such as the density of the streets, the shape and layout of the network (e.g., grid-like, radial, irregular), and the location of the most prominent elements (e.g., intersections, highways, main roads, clusters of streets). For example: "The image shows a dense grid-like street network in the center, with a radial pattern of highways extending outward. The main intersections are located in the top-left and bottom-right corners."
            Start the description from the more general aspects (e.g., "The image shows a dense urban area with a grid-like street network") and then describe the more detailed elements. Avoid using the names of places or streets in the description; focus only on the characteristics of the street network.
            The description should be at least 200 characters.
            Also, return a python list with tags or keywords that describe the image. There should be 10 tags. The format is this ["tag1","tag2","tag3","tag4","tag5","tag6","tag7","tag8","tag9","tag10"].
            Use tags that describe urban features present in the description, such as "grid", "radial", "dense", "sparse", "intersection", "highway", "main road", "cluster", "irregular", "periphery".
            Do not include any markdown elements in your response, just the description and the list of tags.""", base64_image)
        tags = tags_regex(img_desc)
        tags_str = ','.join(tags)
        desc = desc_regex(img_desc)
        
        new_row = {'country': country, 'city': city, 'street_file_name': filename, 'street_description': desc, 'street_tags': tags_str}
        street_df = pd.concat([street_df, pd.DataFrame([new_row])], ignore_index=True)

Processing 1 of 1365 images: Surat, India_street_network.png
city: Surat, country: India
Processing 2 of 1365 images: Moscow, Russia_street_network.png
city: Moscow, country: Russia
Processing 3 of 1365 images: Rome, Italy_street_network.png
city: Rome, country: Italy
Processing 4 of 1365 images: Quito, Ecuador_street_network.png
city: Quito, country: Ecuador
Processing 5 of 1365 images: Kalamata, Greece_street_network.png
city: Kalamata, country: Greece
Processing 6 of 1365 images: Francistown, Botswana_street_network.png
city: Francistown, country: Botswana
Processing 7 of 1365 images: Dharan, Nepal_street_network.png
city: Dharan, country: Nepal
Processing 8 of 1365 images: Differdange, Luxembourg_street_network.png
city: Differdange, country: Luxembourg
Processing 9 of 1365 images: Monrovia, Liberia_street_network.png
city: Monrovia, country: Liberia
Processing 10 of 1365 images: Mazatenango, Guatemala_street_network.png
city: Mazatenango, country: Guatemala
Processing 11 of 1365 images: Mons, Belgium_street_network.png
city: Mons, country: Belgium
Processing 12 of 1365 images: Fergana, Uzbekistan_street_network.png
city: Fergana, country: Uzbekistan
Processing 13 of 1365 images: Malmo, Sweden_street_network.png
city: Malmo, country: Sweden
Processing 14 of 1365 images: Bafatá, Guinea-Bissau_street_network.png
city: Bafatá, country: Guinea-Bissau
Processing 15 of 1365 images: Madurai, India_street_network.png
city: Madurai, country: India
Processing 16 of 1365 images: Assab, Eritrea_street_network.png
city: Assab, country: Eritrea
Processing 17 of 1365 images: Segou, Mali_street_network.png
city: Segou, country: Mali
Processing 18 of 1365 images: Brescia, Italy_street_network.png
city: Brescia, country: Italy
Processing 19 of 1365 images: Kingstown, Saint Vincent and the Grenadines_street_network.png
city: Kingstown, country: Saint Vincent and the Grenadines
Processing 20 of 1365 images: Biratnagar, Nepal_street_network.png
city: Biratnagar, country: Nepal
Processing 21 of 1365 images: Maceió, Brazil_street_network.png
city: Maceió, country: Brazil
Processing 22 of 1365 images: Bulawayo, Zimbabwe_street_network.png
city: Bulawayo, country: Zimbabwe
Processing 23 of 1365 images: Gjilan, Kosovo_street_network.png
city: Gjilan, country: Kosovo
Processing 24 of 1365 images: Cape Town, South Africa_street_network.png
city: Cape Town, country: South Africa
Processing 25 of 1365 images: Johor Bahru, Malaysia_street_network.png
city: Johor Bahru, country: Malaysia
Processing 26 of 1365 images: Kitwe, Zambia_street_network.png
city: Kitwe, country: Zambia
Processing 27 of 1365 images: Meknes, Morocco_street_network.png
city: Meknes, country: Morocco
Processing 28 of 1365 images: Mabaruma, Guyana_street_network.png
city: Mabaruma, country: Guyana
Processing 29 of 1365 images: Bria, Central African Republic_street_network.png
city: Bria, country: Central African Republic
Processing 30 of 1365 images: Najaf, Iraq_street_network.png
city: Najaf, country: Iraq
Processing 31 of 1365 images: Setubal, Portugal_street_network.png
city: Setubal, country: Portugal
Processing 32 of 1365 images: Gyumri, Armenia_street_network.png
city: Gyumri, country: Armenia
Processing 33 of 1365 images: Roskilde, Denmark_street_network.png
city: Roskilde, country: Denmark
Processing 34 of 1365 images: Nicosia, Cyprus_street_network.png
city: Nicosia, country: Cyprus
Processing 35 of 1365 images: Massawa, Eritrea_street_network.png
city: Massawa, country: Eritrea
Processing 36 of 1365 images: Ilorin, Nigeria_street_network.png
city: Ilorin, country: Nigeria
Processing 37 of 1365 images: Szombathely, Hungary_street_network.png
city: Szombathely, country: Hungary
Processing 38 of 1365 images: Patras, Greece_street_network.png
city: Patras, country: Greece
Processing 39 of 1365 images: Barquisimeto, Venezuela_street_network.png
city: Barquisimeto, country: Venezuela
Processing 40 of 1365 images: Pune, India_street_network.png
city: Pune, country: India
Processing 41 of 1365 images: Natal, Brazil_street_network.png
city: Natal, country: Brazil
Processing 42 of 1365 images: Valencia, Venezuela_street_network.png
city: Valencia, country: Venezuela
Processing 43 of 1365 images: Asmara, Eritrea_street_network.png
city: Asmara, country: Eritrea
Processing 44 of 1365 images: Hamilton, Canada_street_network.png
city: Hamilton, country: Canada
Processing 45 of 1365 images: Taipa, Macau_street_network.png
city: Taipa, country: Macau
Processing 46 of 1365 images: Jacksonville, United States_street_network.png
city: Jacksonville, country: United States
Processing 47 of 1365 images: Bilbao, Spain_street_network.png
city: Bilbao, country: Spain
Processing 48 of 1365 images: Taurage, Lithuania_street_network.png
city: Taurage, country: Lithuania
Processing 49 of 1365 images: Isa Town, Bahrain_street_network.png
city: Isa Town, country: Bahrain
Processing 50 of 1365 images: Lethem, Guyana_street_network.png
city: Lethem, country: Guyana
Processing 51 of 1365 images: Bimbo, Central African Republic_street_network.png
city: Bimbo, country: Central African Republic
Processing 52 of 1365 images: Auckland, New Zealand_street_network.png
city: Auckland, country: New Zealand
Processing 53 of 1365 images: Newcastle, United Kingdom_street_network.png
city: Newcastle, country: United Kingdom
Processing 54 of 1365 images: Bergen, Norway_street_network.png
city: Bergen, country: Norway
Processing 55 of 1365 images: Herat, Afghanistan_street_network.png
city: Herat, country: Afghanistan
Processing 56 of 1365 images: Takoradi, Ghana_street_network.png
city: Takoradi, country: Ghana
Processing 57 of 1365 images: Apopa, El Salvador_street_network.png
city: Apopa, country: El Salvador
Processing 58 of 1365 images: Jelgava, Latvia_street_network.png
city: Jelgava, country: Latvia
Processing 59 of 1365 images: Kanye, Botswana_street_network.png
city: Kanye, country: Botswana
Processing 60 of 1365 images: Lobito, Angola_street_network.png
city: Lobito, country: Angola
Processing 61 of 1365 images: Nanjing, China_street_network.png
city: Nanjing, country: China
Processing 62 of 1365 images: Barranquilla, Colombia_street_network.png
city: Barranquilla, country: Colombia
Processing 63 of 1365 images: Esch-sur-Alzette, Luxembourg_street_network.png
city: Esch-sur-Alzette, country: Luxembourg
Processing 64 of 1365 images: Nuku'alofa, Tonga_street_network.png
city: Nuku'alofa, country: Tonga
Processing 65 of 1365 images: Janakpur, Nepal_street_network.png
city: Janakpur, country: Nepal
Processing 66 of 1365 images: Baghdad, Iraq_street_network.png
city: Baghdad, country: Iraq
Processing 67 of 1365 images: Alexandria, Egypt_street_network.png
city: Alexandria, country: Egypt
Processing 68 of 1365 images: Vejle, Denmark_street_network.png
city: Vejle, country: Denmark
Processing 69 of 1365 images: Sialkot, Pakistan_street_network.png
city: Sialkot, country: Pakistan
Processing 70 of 1365 images: Aswan, Egypt_street_network.png
city: Aswan, country: Egypt
Processing 71 of 1365 images: Quatre Bornes, Mauritius_street_network.png
city: Quatre Bornes, country: Mauritius
Processing 72 of 1365 images: Kismayo, Somalia_street_network.png
city: Kismayo, country: Somalia
Processing 73 of 1365 images: Birmingham, United Kingdom_street_network.png
city: Birmingham, country: United Kingdom
Processing 74 of 1365 images: Bairiki, Kiribati_street_network.png
city: Bairiki, country: Kiribati
Processing 75 of 1365 images: Naypyidaw, Myanmar_street_network.png
city: Naypyidaw, country: Myanmar
Processing 76 of 1365 images: Rzeszow, Poland_street_network.png
city: Rzeszow, country: Poland
Processing 77 of 1365 images: Podgorica, Montenegro_street_network.png
city: Podgorica, country: Montenegro
Processing 78 of 1365 images: Wroclaw, Poland_street_network.png
city: Wroclaw, country: Poland
Processing 79 of 1365 images: Phuentsholing, Bhutan_street_network.png
city: Phuentsholing, country: Bhutan
Processing 80 of 1365 images: Visakhapatnam, India_street_network.png
city: Visakhapatnam, country: India
Processing 81 of 1365 images: Ghaziabad, India_street_network.png
city: Ghaziabad, country: India
Processing 82 of 1365 images: Philadelphia, United States_street_network.png
city: Philadelphia, country: United States
Processing 83 of 1365 images: Nassau, Bahamas_street_network.png
city: Nassau, country: Bahamas
Processing 84 of 1365 images: Luang Prabang, Laos_street_network.png
city: Luang Prabang, country: Laos
Processing 85 of 1365 images: Mechelen, Belgium_street_network.png
city: Mechelen, country: Belgium
Processing 86 of 1365 images: Celje, Slovenia_street_network.png
city: Celje, country: Slovenia
Processing 87 of 1365 images: Bosaso, Somalia_street_network.png
city: Bosaso, country: Somalia
Processing 88 of 1365 images: Assomada, Cape Verde_street_network.png
city: Assomada, country: Cape Verde
Processing 89 of 1365 images: Rosso, Mauritania_street_network.png
city: Rosso, country: Mauritania
Processing 90 of 1365 images: Bhopal, India_street_network.png
city: Bhopal, country: India
Processing 91 of 1365 images: Steyr, Austria_street_network.png
city: Steyr, country: Austria
Processing 92 of 1365 images: Malabo, Equatorial Guinea_street_network.png
city: Malabo, country: Equatorial Guinea
Processing 93 of 1365 images: Khost, Afghanistan_street_network.png
city: Khost, country: Afghanistan
Processing 94 of 1365 images: Cacheu, Guinea-Bissau_street_network.png
city: Cacheu, country: Guinea-Bissau
Processing 95 of 1365 images: La Ceiba, Honduras_street_network.png
city: La Ceiba, country: Honduras
Processing 96 of 1365 images: Sofia, Bulgaria_street_network.png
city: Sofia, country: Bulgaria
Processing 97 of 1365 images: Tartu, Estonia_street_network.png
city: Tartu, country: Estonia
Processing 98 of 1365 images: Cluj-Napoca, Romania_street_network.png
city: Cluj-Napoca, country: Romania
Processing 99 of 1365 images: São Luís, Brazil_street_network.png
city: São Luís, country: Brazil
Processing 100 of 1365 images: Zahle, Lebanon_street_network.png
city: Zahle, country: Lebanon
Processing 101 of 1365 images: Bissau, Guinea-Bissau_street_network.png
city: Bissau, country: Guinea-Bissau
Processing 102 of 1365 images: Saint-Étienne, France_street_network.png
city: Saint-Étienne, country: France
Processing 103 of 1365 images: Lelydorp, Suriname_street_network.png
city: Lelydorp, country: Suriname
Processing 104 of 1365 images: Bharatpur, Nepal_street_network.png
city: Bharatpur, country: Nepal
Processing 105 of 1365 images: Owerri, Nigeria_street_network.png
city: Owerri, country: Nigeria
Processing 106 of 1365 images: Niš, Serbia_street_network.png
city: Niš, country: Serbia
Processing 107 of 1365 images: Kota Kinabalu, Malaysia_street_network.png
city: Kota Kinabalu, country: Malaysia
Processing 108 of 1365 images: Danli, Honduras_street_network.png
city: Danli, country: Honduras
Processing 109 of 1365 images: Mostaganem, Algeria_street_network.png
city: Mostaganem, country: Algeria
Processing 110 of 1365 images: Farwaniya, Kuwait_street_network.png
city: Farwaniya, country: Kuwait
Processing 111 of 1365 images: Olanchito, Honduras_street_network.png
city: Olanchito, country: Honduras
Processing 112 of 1365 images: Puerto La Cruz, Venezuela_street_network.png
city: Puerto La Cruz, country: Venezuela
Processing 113 of 1365 images: Kecskemet, Hungary_street_network.png
city: Kecskemet, country: Hungary
Processing 114 of 1365 images: Durres, Albania_street_network.png
city: Durres, country: Albania
Processing 115 of 1365 images: Marrakech, Morocco_street_network.png
city: Marrakech, country: Morocco
Processing 116 of 1365 images: Victoria, Canada_street_network.png
city: Victoria, country: Canada
Processing 117 of 1365 images: Barcelona, Spain_street_network.png
city: Barcelona, country: Spain
Processing 118 of 1365 images: Sao Paulo, Brazil_street_network.png
city: Sao Paulo, country: Brazil
Processing 119 of 1365 images: Lusaka, Zambia_street_network.png
city: Lusaka, country: Zambia
Processing 120 of 1365 images: Khartoum, Sudan_street_network.png
city: Khartoum, country: Sudan
Processing 121 of 1365 images: Port Said, Egypt_street_network.png
city: Port Said, country: Egypt
Processing 122 of 1365 images: Tauranga, New Zealand_street_network.png
city: Tauranga, country: New Zealand
Processing 123 of 1365 images: Almeria, Spain_street_network.png
city: Almeria, country: Spain
Processing 124 of 1365 images: Abu Dhabi, United Arab Emirates_street_network.png
city: Abu Dhabi, country: United Arab Emirates
Processing 125 of 1365 images: Bucharest, Romania_street_network.png
city: Bucharest, country: Romania
Processing 126 of 1365 images: Thakhek, Laos_street_network.png
city: Thakhek, country: Laos
Processing 127 of 1365 images: San Salvador, El Salvador_street_network.png
city: San Salvador, country: El Salvador
Processing 128 of 1365 images: Gizo, Solomon Islands_street_network.png
city: Gizo, country: Solomon Islands
Processing 129 of 1365 images: Multan, Pakistan_street_network.png
city: Multan, country: Pakistan
Processing 130 of 1365 images: Juliaca, Peru_street_network.png
city: Juliaca, country: Peru
Processing 131 of 1365 images: Temuco, Chile_street_network.png
city: Temuco, country: Chile
Processing 132 of 1365 images: Rotterdam, Netherlands_street_network.png
city: Rotterdam, country: Netherlands
Processing 133 of 1365 images: Cobán, Guatemala_street_network.png
city: Cobán, country: Guatemala
Processing 134 of 1365 images: Feldkirch, Austria_street_network.png
city: Feldkirch, country: Austria
Processing 135 of 1365 images: Usulutan, El Salvador_street_network.png
city: Usulutan, country: El Salvador
Processing 136 of 1365 images: Korce, Albania_street_network.png
city: Korce, country: Albania
Processing 137 of 1365 images: Waterford, Ireland_street_network.png
city: Waterford, country: Ireland
Processing 138 of 1365 images: Mawlamyine, Myanmar_street_network.png
city: Mawlamyine, country: Myanmar
Processing 139 of 1365 images: Nottingham, United Kingdom_street_network.png
city: Nottingham, country: United Kingdom
Processing 140 of 1365 images: Münster, Germany_street_network.png
city: Münster, country: Germany
Processing 141 of 1365 images: Tilburg, Netherlands_street_network.png
city: Tilburg, country: Netherlands
Processing 142 of 1365 images: Addis Ababa, Ethiopia_street_network.png
city: Addis Ababa, country: Ethiopia
Processing 143 of 1365 images: Wolverhampton, United Kingdom_street_network.png
city: Wolverhampton, country: United Kingdom
Processing 144 of 1365 images: Tipitapa, Nicaragua_street_network.png
city: Tipitapa, country: Nicaragua
Processing 145 of 1365 images: Lambarene, Gabon_street_network.png
city: Lambarene, country: Gabon
Processing 146 of 1365 images: Limassol, Cyprus_street_network.png
city: Limassol, country: Cyprus
Processing 147 of 1365 images: Gondar, Ethiopia_street_network.png
city: Gondar, country: Ethiopia
Processing 148 of 1365 images: Coventry, United Kingdom_street_network.png
city: Coventry, country: United Kingdom
Processing 149 of 1365 images: Dili, East Timor_street_network.png
city: Dili, country: East Timor
Processing 150 of 1365 images: Cologne, Germany_street_network.png
city: Cologne, country: Germany
Processing 151 of 1365 images: New York, USA_street_network.png
city: New York, country: USA
Processing 152 of 1365 images: Coloane, Macau_street_network.png
city: Coloane, country: Macau
Processing 153 of 1365 images: Dolisie, Republic of the Congo_street_network.png
city: Dolisie, country: Republic of the Congo
Processing 154 of 1365 images: Banska Bystrica, Slovakia_street_network.png
city: Banska Bystrica, country: Slovakia
Processing 155 of 1365 images: Am Timan, Chad_street_network.png
city: Am Timan, country: Chad
Processing 156 of 1365 images: Vientiane, Laos_street_network.png
city: Vientiane, country: Laos
Processing 157 of 1365 images: Wiesbaden, Germany_street_network.png
city: Wiesbaden, country: Germany
Processing 158 of 1365 images: Hargeisa, Somalia_street_network.png
city: Hargeisa, country: Somalia
Processing 159 of 1365 images: Aalst, Belgium_street_network.png
city: Aalst, country: Belgium
Processing 160 of 1365 images: Liberec, Czech Republic_street_network.png
city: Liberec, country: Czech Republic
Processing 161 of 1365 images: Taipei, Taiwan_street_network.png
city: Taipei, country: Taiwan
Processing 162 of 1365 images: Quepos, Costa Rica_street_network.png
city: Quepos, country: Costa Rica
Processing 163 of 1365 images: Paphos, Cyprus_street_network.png
city: Paphos, country: Cyprus
Processing 164 of 1365 images: Chennai, India_street_network.png
city: Chennai, country: India
Processing 165 of 1365 images: Aveiro, Portugal_street_network.png
city: Aveiro, country: Portugal
Processing 166 of 1365 images: Turku, Finland_street_network.png
city: Turku, country: Finland
Processing 167 of 1365 images: Bukhara, Uzbekistan_street_network.png
city: Bukhara, country: Uzbekistan
Processing 168 of 1365 images: Ijevan, Armenia_street_network.png
city: Ijevan, country: Armenia
Processing 169 of 1365 images: Sibiu, Romania_street_network.png
city: Sibiu, country: Romania
Processing 170 of 1365 images: Latakia, Syria_street_network.png
city: Latakia, country: Syria
Processing 171 of 1365 images: Sumqayit, Azerbaijan_street_network.png
city: Sumqayit, country: Azerbaijan
Processing 172 of 1365 images: Sirte, Libya_street_network.png
city: Sirte, country: Libya
Processing 173 of 1365 images: Sabha, Libya_street_network.png
city: Sabha, country: Libya
Processing 174 of 1365 images: Mu'a, Tonga_street_network.png
city: Mu'a, country: Tonga
Processing 175 of 1365 images: Mzuzu, Malawi_street_network.png
city: Mzuzu, country: Malawi
Processing 176 of 1365 images: Poti, Georgia_street_network.png
city: Poti, country: Georgia
Processing 177 of 1365 images: Yamoussoukro, Ivory Coast_street_network.png
city: Yamoussoukro, country: Ivory Coast
Processing 178 of 1365 images: Mutsamudu, Comoros_street_network.png
city: Mutsamudu, country: Comoros
Processing 179 of 1365 images: Sonsonate, El Salvador_street_network.png
city: Sonsonate, country: El Salvador
Processing 180 of 1365 images: Hawassa, Ethiopia_street_network.png
city: Hawassa, country: Ethiopia
Processing 181 of 1365 images: Qom, Iran_street_network.png
city: Qom, country: Iran
Processing 182 of 1365 images: La Coruna, Spain_street_network.png
city: La Coruna, country: Spain
Processing 183 of 1365 images: Khujand, Tajikistan_street_network.png
city: Khujand, country: Tajikistan
Processing 184 of 1365 images: Ajman, United Arab Emirates_street_network.png
city: Ajman, country: United Arab Emirates
Processing 185 of 1365 images: Tabriz, Iran_street_network.png
city: Tabriz, country: Iran
Processing 186 of 1365 images: Kitakyushu, Japan_street_network.png
city: Kitakyushu, country: Japan
Processing 187 of 1365 images: Tel Aviv, Israel_street_network.png
city: Tel Aviv, country: Israel
Processing 188 of 1365 images: Belém, Brazil_street_network.png
city: Belém, country: Brazil
Processing 189 of 1365 images: Zomba, Malawi_street_network.png
city: Zomba, country: Malawi
Processing 190 of 1365 images: Famagusta, Cyprus_street_network.png
city: Famagusta, country: Cyprus
Processing 191 of 1365 images: Antwerp, Belgium_street_network.png
city: Antwerp, country: Belgium
Processing 192 of 1365 images: Nukus, Uzbekistan_street_network.png
city: Nukus, country: Uzbekistan
Processing 193 of 1365 images: Presov, Slovakia_street_network.png
city: Presov, country: Slovakia
Processing 194 of 1365 images: Austin, United States_street_network.png
city: Austin, country: United States
Processing 195 of 1365 images: Mosul, Iraq_street_network.png
city: Mosul, country: Iraq
Processing 196 of 1365 images: Valencia, Spain_street_network.png
city: Valencia, country: Spain
Processing 197 of 1365 images: Sarh, Chad_street_network.png
city: Sarh, country: Chad
Processing 198 of 1365 images: Rancagua, Chile_street_network.png

In [295]:
street_df

,country,city,street_file_name,street_description,street_tags
0,India,Surat,"Surat, India_street_network.png",The image shows a dense urban area with a high...,"grid, dense, irregular, intersection, main roa..."
1,Russia,Moscow,"Moscow, Russia_street_network.png",The image shows a dense urban area at the cent...,"radial,dense,intersection,main road,highway,cl..."
2,Italy,Rome,"Rome, Italy_street_network.png",The image shows a dense urban area with an irr...,"dense, irregular, radial, main road, highway, ..."
3,Ecuador,Quito,"Quito, Ecuador_street_network.png",The image shows a dense urban area with a mix ...,"dense,grid,irregular,main road,intersection,cl..."
4,Greece,Kalamata,"Kalamata, Greece_street_network.png",The image shows a dense urban area near the so...,"dense,grid,irregular,main road,intersection,cl..."
...,...,...,...,...,...
1360,Oman,Nizwa,"Nizwa, Oman_street_network.png",The image shows a moderately dense urban area ...,"dense,grid,irregular,radial,main road,intersec..."
1361,Zimbabwe,Marondera,"Marondera, Zimbabwe_street_network.png",The image shows a moderately dense urban area ...,"grid,irregular,dense,cluster,main road,interse..."
1362,Brazil,Campinas,"Campinas, Brazil_street_network.png",The image shows a dense urban area with a high...,"grid, dense, radial, main road, intersection, ..."
1363,Guatemala,Mixco,"Mixco, Guatemala_street_network.png",The image shows a highly varied urban area wit...,"grid, dense, irregular, sparse, intersection, ..."
1364,Nigeria,Maiduguri,"Maiduguri, Nigeria_street_network.png",The image shows a dense urban area with a comp...,"grid, radial, dense, irregular, main road, int..."

In [296]:
street_df.to_csv('/home/salvador_cb/3_term/Applied_research_studio/data/csv/street_metadata.csv', index=False, quoting=csv.QUOTE_ALL)

In [245]:
df = pd.DataFrame(columns=["country","city","description","tags"])

In [203]:
df

,country,city,description,tags
0,Lebanon,Beirut,The image shows a coastal region bordered by a...,"coast,ocean,mountain,hill,elevation,slope,upla..."
1,Pakistan,Peshawar,The image displays a generally flat to gently ...,"plain,hill,river,stream,lowland,drainage,eleva..."
2,Denmark,Roskilde,The image displays a coastal terrain with a mi...,"coast,bay,river,estuary,island,peninsula,uplan..."
3,Guyana,Linden,The image shows a region dominated by low-lyin...,"river,plain,valley,tributary,basin,stream,hill..."
4,Azerbaijan,Ganja,The image depicts a landscape dominated by an ...,"valley,river,tributary,ridge,plateau,floodplai..."
...,...,...,...,...
1139,Kazakhstan,Shymkent,The image shows a rugged mountainous region wi...,"mountain,valley,ridge,river,channel,ravine,gul..."
1140,Benin,Porto-Novo,The image presents a flat coastal region with ...,"river,plains,estuary,coast,tributary,wetland,d..."
1141,Bulgaria,Pleven,The image depicts a landscape characterized by...,"valley,hill,ridge,slope,river,watercourse,eros..."
1142,Botswana,Maun,The image displays a gently varied landscape w...,"highland,plain,valley,river,floodplain,elevati..."
1143,Sri Lanka,Colombo,The image shows a coastal region with varying ...,"coast,ocean,hill,plain,river,valley,elevation,..."

In [ ]:
existing_df.to_csv(csv_path, index=False, quoting=csv.QUOTE_ALL)

In [ ]:
img_desc = gpt_vision(f"""You are a model with vision capabilities.
Your task is to generate a description of the images.
Each image shows an overlay of an urban street network on a grayscale topographic map of {city_name_regex(file_path)[0]}, {city_name_regex(file_path)[1]}. In the image, red lines represent streets and pathways, while the grayscale background depicts the terrain. Whiter areas indicate higher elevations and darker areas indicate lower regions.
Return a detailed text description of the image that explains how the urban street network interacts with the underlying topography. Describe how the street layout adapts to the terrain's features. For instance, if a grid structure is nested within a valley, if roads bend to circumnavigate mountain ridges, if a dense node of intersections is located near a coastal margin, or if arterial roads cut through elevated areas. Use specific observations to illustrate this interplay, such as noting a straight, dense grid pattern in flat, low-elevation zones and winding, meandering roads along sharper, elevated contours.
Begin with a general overview of how the urban network is integrated with the natural landscape, then transition into more detailed commentary on particular areas of interest. Do not include any proper names or landmarks; focus solely on describing the physical characteristics and spatial relationships between the urban elements and the terrain. The description must be at least 200 characters.
Additionally, return a Python list with 10 tags or keywords that encapsulate the observed urban and topographic features. The format should be: ["tag1","tag2","tag3","tag4","tag5","tag6","tag7","tag8","tag9","tag10"]. Use only specific descriptive terms related to the image, such as valley, mountain, coast, grid, branching, winding, elevation, intersection, hillside, and contour.
Do not include any markdown formatting in your response; provide only the description and the list of tags.
""", base64_image)

 The image resembles a sample where a dense cluster of red lines in the center branches outward, suggesting a complex, interconnected network that adapts to the natural contours of the land.

In [249]:
df = pd.read_csv('/home/salvador_cb/3_term/Applied_research_studio/data/csv/new_metadata.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1365 entries, 0 to 1364
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   country      1365 non-null   object
 1   city         1365 non-null   object
 2   description  1365 non-null   object
 3   tags         1365 non-null   object
dtypes: object(4)
memory usage: 42.8+ KB

In [365]:
csv_path = '/home/salvador_cb/3_term/Applied_research_studio/data/csv/new_metadata.csv'
if os.path.exists(csv_path):
    existing_df = pd.read_csv(csv_path)
else:
    existing_df = pd.DataFrame(columns=["country", "city", "elevation_file_name", "description", "tags"])

processed_cities = list(zip(existing_df['city'], existing_df['country']))

folder_path = '/home/salvador_cb/3_term/Applied_research_studio/data/img/train/elevation_2'

city_counter = 0
# Loop through all the files in the folder
for filename in os.listdir(folder_path):
    if filename.endswith('.png'):  # Assuming all your images are in PNG format
        # Construct the full file path
        file_path = os.path.join(folder_path, filename)
        city, country = city_name_regex(file_path)
        city_counter += 1
        print(f"Processing {city_counter} of {len(os.listdir(folder_path))} images: {filename}")

        if (city, country) in processed_cities:
            print(f"City {city}, {country} is already processed. Skipping...")
            continue
        
        print(f'city: {city}, country: {country}')
        image_vis = Image.open(file_path)
        base64_image = image_to_base64(image_vis)
        
        # Use regex to extract the city and country names from the filename
        global gptVisionAppPromptTemplate
        gptVisionAppPromptTemplate = f"Here is a topograpical map of the city {city}, {country}. give me a description and tags of the topographical characteristics."

        img_desc = gpt_vision(f"""You are a model with vision capabilities.
            Your task is to generate a description of the images.
            each image shows the topography of {city}, {country}.
            The altitude is represented with a grayscale color gradient, where the whitest areas are the tallest and the darkest areas are at the bottom. the whiter the pixel the higher the point is.
            Return a text description of the image, describing the topographical features (rivers, ocean, mountains, valleys, plains, etc...). describe where the elements are located in the image, and their relative size and shape. For example: 3 mountains in the top and a river crossing the image from left to right. The mountains are large and slopped, while the river is thin and winding.
            Start the description from the more general aspects (the image shows an island, the image shows a valley, etc ...) and then describe the more detailed elements. Use the name of the place better identify what the topographical elements are (if its an ocean or a lake). Do not use name of places in the description, such as the city name or name of a river, only the characteristics of the terrain. The description be at least 200 characters.
            also, return a python list with tags or keywords that describe the image. there should be 10 tags. the format is this ["tag1","tag2","tag3","tag4","tag5","tag6","tag7","tag8","tag9","tag10"].
            Do not use tags such as topography or elevation. Use only topographical features present in the description, such as ocean, mountain, river, lake, valley, island, coast, etc...
            Do not include any markdown elements in your response, just the description and the list of tags.""", base64_image)
        tags = tags_regex(img_desc)
        tags_str = ','.join(tags)
        desc = desc_regex(img_desc)
        
        new_row = {'country': country, 'city': city, 'elevation_file_name': filename}
        existing_df = pd.concat([existing_df, pd.DataFrame([new_row])], ignore_index=True)

Processing 1 of 1365 images: Beirut, Lebanon_elevation.png
city: None, country: None
Processing 2 of 1365 images: Peshawar, Pakistan_elevation.png
city: None, country: None
Processing 3 of 1365 images: Roskilde, Denmark_elevation.png
city: None, country: None
Processing 4 of 1365 images: Linden, Guyana_elevation.png
city: None, country: None

KeyboardInterrupt:

In [366]:
existing_df

,country,city,description,tags,elevation_file_name
0,Lebanon,Beirut,The image shows a coastal region bordered by a...,"coast,ocean,mountain,hill,elevation,slope,upla...",NaN
1,Pakistan,Peshawar,The image displays a generally flat to gently ...,"plain,hill,river,stream,lowland,drainage,eleva...",NaN
2,Denmark,Roskilde,The image displays a coastal terrain with a mi...,"coast,bay,river,estuary,island,peninsula,uplan...",NaN
3,Guyana,Linden,The image shows a region dominated by low-lyin...,"river,plain,valley,tributary,basin,stream,hill...",NaN
4,Azerbaijan,Ganja,The image depicts a landscape dominated by an ...,"valley,river,tributary,ridge,plateau,floodplai...",NaN
...,...,...,...,...,...
1363,UK,Leeds,The image depicts a rugged and hilly landscape...,"valley,river,ridge,hill,ravine,channel,highlan...",NaN
1364,United Kingdom,London,The image shows a varied inland terrain charac...,"valley,river,upland,highlands,hill,tributary,r...",NaN
1365,None,None,NaN,NaN,"Beirut, Lebanon_elevation.png"
1366,None,None,NaN,NaN,"Peshawar, Pakistan_elevation.png"
1367,None,None,NaN,NaN,"Roskilde, Denmark_elevation.png"

In [ ]:
existing_df.to_csv(csv_path, index=False, quoting=csv.QUOTE_ALL)

In [204]:
df.to_csv('/home/salvador_cb/3_term/Applied_research_studio/data/csv/new_metadata.csv', index=False, quoting=csv.QUOTE_ALL)

In [370]:
import pandas as pd
import os

# Path to the CSV file
csv_path = '/home/salvador_cb/3_term/Applied_research_studio/data/csv/new_metadata.csv'

# Load the existing CSV
if os.path.exists(csv_path):
    df = pd.read_csv(csv_path)
else:
    raise FileNotFoundError(f"{csv_path} does not exist.")

# Ensure the column is added after 'city'
if 'elevation_file_name' not in df.columns:
    df.insert(df.columns.get_loc('city') + 1, 'elevation_file_name', '')

# Define the folder containing elevation files
elevation_folder = '/home/salvador_cb/3_term/Applied_research_studio/data/img/train/elevation_2'

# Loop through the rows and populate the 'elevation_file_name' column
for index, row in df.iterrows():
    city = row['city']
    country = row['country']
    elevation_file = f"{city}, {country}_elevation.png"
    print(elevation_file)
    elevation_file_path = os.path.join(elevation_folder, elevation_file)
    
    # Check if the file exists
    if os.path.exists(elevation_file_path):
        df.at[index, 'elevation_file_name'] = elevation_file
    else:
        df.at[index, 'elevation_file_name'] = None  # Set to None if the file doesn't exist

# Save the updated DataFrame back to the CSV

Beirut, Lebanon_elevation.png
Peshawar, Pakistan_elevation.png
Roskilde, Denmark_elevation.png
Linden, Guyana_elevation.png
Ganja, Azerbaijan_elevation.png
Ettelbruck, Luxembourg_elevation.png
Amsterdam, Netherlands_elevation.png
Male, Maldives_elevation.png
Schaan, Liechtenstein_elevation.png
Kutaisi, Georgia_elevation.png
Lugano, Switzerland_elevation.png
Taipei, Taiwan_elevation.png
Kohtla-Jarve, Estonia_elevation.png
Charleroi, Belgium_elevation.png
Hobart, Australia_elevation.png
Maturin, Venezuela_elevation.png
Villavicencio, Colombia_elevation.png
Montreal, Canada_elevation.png
Sucre, Bolivia_elevation.png
Bucharest, Romania_elevation.png
Tsuen Wan, Hong Kong_elevation.png
Heredia, Costa Rica_elevation.png
Belfast, United Kingdom_elevation.png
Liverpool, United Kingdom_elevation.png
Serowe, Botswana_elevation.png
La Serena, Chile_elevation.png
Osijek, Croatia_elevation.png
Turin, Italy_elevation.png
Kaga-Bandoro, Central African Republic_elevation.png
Kaduna, Nigeria_elevation.png
Cartago, Costa Rica_elevation.png
Puerto Cortes, Honduras_elevation.png
Punto Fijo, Venezuela_elevation.png
Panevezys, Lithuania_elevation.png
Timisoara, Romania_elevation.png
Buenos Aires, Argentina_elevation.png
Sapporo, Japan_elevation.png
Mbarara, Uganda_elevation.png
Port Moresby, Papua New Guinea_elevation.png
Masaya, Nicaragua_elevation.png
Bokhtar, Tajikistan_elevation.png
Kiev, Ukraine_elevation.png
Quatre Bornes, Mauritius_elevation.png
El Jadida, Morocco_elevation.png
Wels, Austria_elevation.png
Szczecin, Poland_elevation.png
Kairouan, Tunisia_elevation.png
Padua, Italy_elevation.png
Singapore, Singapore_elevation.png
Quetzaltenango, Guatemala_elevation.png
Manzini, Eswatini_elevation.png
Lisbon, Portugal_elevation.png
Mahajanga, Madagascar_elevation.png
Jaffna, Sri Lanka_elevation.png
Berat, Albania_elevation.png
Durres, Albania_elevation.png
Victoria, Canada_elevation.png
Fredrikstad, Norway_elevation.png
Beira, Mozambique_elevation.png
Barquisimeto, Venezuela_elevation.png
Maroua, Cameroon_elevation.png
Arica, Chile_elevation.png
Apeldoorn, Netherlands_elevation.png
Retalhuleu, Guatemala_elevation.png
Budva, Montenegro_elevation.png
Horsens, Denmark_elevation.png
Kathmandu, Nepal_elevation.png
Derna, Libya_elevation.png
Phoenix, USA_elevation.png
Roatan, Honduras_elevation.png
Saint Etienne, France_elevation.png
Santiago, Chile_elevation.png
Jinja, Uganda_elevation.png
Mbuji-Mayi, Democratic Republic of the Congo_elevation.png
Bordeaux, France_elevation.png
Estelí, Nicaragua_elevation.png
Dangriga, Belize_elevation.png
Brussels, Belgium_elevation.png
Adelaide, Australia_elevation.png
Gjilan, Kosovo_elevation.png
Cuenca, Ecuador_elevation.png
Kulob, Tajikistan_elevation.png
Colón, Panama_elevation.png
Chalatenango, El Salvador_elevation.png
Malang, Indonesia_elevation.png
Taranto, Italy_elevation.png
Venice, Italy_elevation.png
Bhopal, India_elevation.png
Bangalore, India_elevation.png
Herceg Novi, Montenegro_elevation.png
Zomba, Malawi_elevation.png
Canberra, Australia_elevation.png
Agadez, Niger_elevation.png
Havana, Cuba_elevation.png
Montero, Bolivia_elevation.png
Vacoas-Phoenix, Mauritius_elevation.png
Las Piedras, Uruguay_elevation.png
Vadodara, India_elevation.png
Milan, Italy_elevation.png
Dili, East Timor_elevation.png
Francistown, Botswana_elevation.png
Bor, South Sudan_elevation.png
Gwangju, South Korea_elevation.png
Kokand, Uzbekistan_elevation.png
Zahle, Lebanon_elevation.png
Malacca, Malaysia_elevation.png
Iquitos, Peru_elevation.png
Naples, Italy_elevation.png
Malmo, Sweden_elevation.png
Bijelo Polje, Montenegro_elevation.png
Pristina, Kosovo_elevation.png
Toamasina, Madagascar_elevation.png
Sohar, Oman_elevation.png
Salt, Jordan_elevation.png
Kourou, French Guiana_elevation.png
Ipoh, Malaysia_elevation.png
Santa Ana, El Salvador_elevation.png
Halifax, Canada_elevation.png
Toliara, Madagascar_elevation.png
Denigomodu, Nauru_elevation.png
Aalst, Belgium_elevation.png
Klagenfurt, Austria_elevation.png
Auki, Solomon Islands_elevation.png
Dushanbe, Tajikistan_elevation.png
Damietta, Egypt_elevation.png
Almaty, Kazakhstan_elevation.png
Essen, Germany_elevation.png
Onitsha, Nigeria_elevation.png
Machala, Ecuador_elevation.png
Utena, Lithuania_elevation.png
Munich, Germany_elevation.png
Kisangani, Democratic Republic of the Congo_elevation.png
Serrekunda, Gambia_elevation.png
Oyem, Gabon_elevation.png
Porto, Portugal_elevation.png
Fergana, Uzbekistan_elevation.png
La Lima, Honduras_elevation.png
Yokohama, Japan_elevation.png
Chennai, India_elevation.png
Leuven, Belgium_elevation.png
Antwerp, Belgium_elevation.png
Banjul, Gambia_elevation.png
Bregenz, Austria_elevation.png
Ho, Ghana_elevation.png
Livingstone, Zambia_elevation.png
Sousse, Tunisia_elevation.png
Faisalabad, Pakistan_elevation.png
Delhi, India_elevation.png
Braga, Portugal_elevation.png
Athens, Greece_elevation.png
Cucuta, Colombia_elevation.png
Ulsan, South Korea_elevation.png
Natitingou, Benin_elevation.png
Bamenda, Cameroon_elevation.png
Fada N'gourma, Burkina Faso_elevation.png
Stockholm, Sweden_elevation.png
Abidjan, Ivory Coast_elevation.png
Pardubice, Czech Republic_elevation.png
Pointe-Noire, Republic of the Congo_elevation.png
Babahoyo, Ecuador_elevation.png
Comayagua, Honduras_elevation.png
Philadelphia, United States_elevation.png
Herat, Afghanistan_elevation.png
Ghazni, Afghanistan_elevation.png
Nicoya, Costa Rica_elevation.png
Mindelo, Cape Verde_elevation.png
Larnaca, Cyprus_elevation.png
Leeds, United Kingdom_elevation.png
Madrid, Spain_elevation.png
Assomada, Cape Verde_elevation.png
Ziguinchor, Senegal_elevation.png
Petah Tikva, Israel_elevation.png
Maiduguri, Nigeria_elevation.png
Faiyum, Egypt_elevation.png
Bo, Sierra Leone_elevation.png
Jaipur, India_elevation.png
Oradea, Romania_elevation.png
Maracaibo, Venezuela_elevation.png
Belém, Brazil_elevation.png
Craiova, Romania_elevation.png
Hong Kong, China_elevation.png
Entebbe, Uganda_elevation.png
New York, USA_elevation.png
Tainan, Taiwan_elevation.png
Nottingham, United Kingdom_elevation.png
Regina, Canada_elevation.png
Linkoping, Sweden_elevation.png
Tipitapa, Nicaragua_elevation.png
Santo António, São Tomé and Príncipe_elevation.png
Differdange, Luxembourg_elevation.png
Ngaoundere, Cameroon_elevation.png
Cairns, Australia_elevation.png
Zadar, Croatia_elevation.png
Valdivia, Chile_elevation.png
Bydgoszcz, Poland_elevation.png
Parakou, Benin_elevation.png
Massawa, Eritrea_elevation.png
Ciudad Guayana, Venezuela_elevation.png
Modena, Italy_elevation.png
Ouahigouya, Burkina Faso_elevation.png
Rivas, Nicaragua_elevation.png
Ravenna, Italy_elevation.png
Matara, Sri Lanka_elevation.png
Saint-Georges, French Guiana_elevation.png
Patras, Greece_elevation.png
Paramaribo, Suriname_elevation.png
Garoua, Cameroon_elevation.png
Darwin, Australia_elevation.png
Kandy, Sri Lanka_elevation.png
Belfast, UK_elevation.png
Odessa, Ukraine_elevation.png
Jos, Nigeria_elevation.png
Juba, South Sudan_elevation.png
Alexandroupoli, Greece_elevation.png
Honiara, Solomon Islands_elevation.png
Nadi, Fiji_elevation.png
Tarapoto, Peru_elevation.png
Kandi, Benin_elevation.png
Lushnje, Albania_elevation.png
Johannesburg, South Africa_elevation.png
Chania, Greece_elevation.png
Bogra, Bangladesh_elevation.png
Barcelona, Venezuela_elevation.png
Valencia, Spain_elevation.png
Harare, Zimbabwe_elevation.png
Ahuachapan, El Salvador_elevation.png
Port Harcourt, Nigeria_elevation.png
San Salvador, El Salvador_elevation.png
Ploiesti, Romania_elevation.png
Owando, Republic of the Congo_elevation.png
Konya, Turkey_elevation.png
Eindhoven, Netherlands_elevation.png
Mogadishu, Somalia_elevation.png
Bari, Italy_elevation.png
Deir ez-Zor, Syria_elevation.png
Praia, Cape Verde_elevation.png
Vejle, Denmark_elevation.png
Zugdidi, Georgia_elevation.png
Kitwe, Zambia_elevation.png
Misrata, Libya_elevation.png
Volos, Greece_elevation.png
Khon Kaen, Thailand_elevation.png
Sarpsborg, Norway_elevation.png
Ibb, Yemen_elevation.png
Oran, Algeria_elevation.png
San Miguel de Tucumán, Argentina_elevation.png
Damascus, Syria_elevation.png
Gagnoa, Ivory Coast_elevation.png
Khartoum, Sudan_elevation.png
Graz, Austria_elevation.png
Curitiba, Brazil_elevation.png
Khost, Afghanistan_elevation.png
Luanda, Angola_elevation.png
Niamey, Niger_elevation.png
Mbabane, Eswatini_elevation.png
George Town, Malaysia_elevation.png
Nieuw Nickerie, Suriname_elevation.png
Christchurch, New Zealand_elevation.png
Wangdue Phodrang, Bhutan_elevation.png
Soyapango, El Salvador_elevation.png
Fianarantsoa, Madagascar_elevation.png
Montevideo, Uruguay_elevation.png
Napier, New Zealand_elevation.png
Thakhek, Laos_elevation.png
Multan, Pakistan_elevation.png
Szeged, Hungary_elevation.png
Medellin, Colombia_elevation.png
Matagalpa, Nicaragua_elevation.png
Kampot, Cambodia_elevation.png
Mingachevir, Azerbaijan_elevation.png
Vancouver, Canada_elevation.png
Mu'a, Tonga_elevation.png
Pekanbaru, Indonesia_elevation.png
Teyateyaneng, Lesotho_elevation.png
Vaduz, Liechtenstein_elevation.png
Kota Kinabalu, Malaysia_elevation.png
Zagreb, Croatia_elevation.png
San Cristobal, Venezuela_elevation.png
Dongguan, China_elevation.png
Turku, Finland_elevation.png
Mutare, Zimbabwe_elevation.png
Pattaya, Thailand_elevation.png
Coronel Oviedo, Paraguay_elevation.png
Prague, Czech Republic_elevation.png
Drogheda, Ireland_elevation.png
Marijampole, Lithuania_elevation.png
Golfito, Costa Rica_elevation.png
Tarawa, Kiribati_elevation.png
Dharan, Nepal_elevation.png
Lucknow, India_elevation.png
Mar del Plata, Argentina_elevation.png
Cleveland, USA_elevation.png
Rotorua, New Zealand_elevation.png
Utrecht, Netherlands_elevation.png
Béjaïa, Algeria_elevation.png
Nîmes, France_elevation.png
Banfora, Burkina Faso_elevation.png
Nuku'alofa, Tonga_elevation.png
Phuket, Thailand_elevation.png
San Jose, Costa Rica_elevation.png
Tunis, Tunisia_elevation.png
Xam Neua, Laos_elevation.png
Gijon, Spain_elevation.png
Ibadan, Nigeria_elevation.png
Port-au-Prince, Haiti_elevation.png
Karlstad, Sweden_elevation.png
Chongjin, North Korea_elevation.png
Basra, Iraq_elevation.png
Samdrup Jongkhar, Bhutan_elevation.png
Porto Alegre, Brazil_elevation.png
Frankfurt, Germany_elevation.png
Juliaca, Peru_elevation.png
Olanchito, Honduras_elevation.png
Lobito, Angola_elevation.png
Ankara, Turkey_elevation.png
Tlemcen, Algeria_elevation.png
Sfax, Tunisia_elevation.png
Salalah, Oman_elevation.png
Hanoi, Vietnam_elevation.png
Blantyre, Malawi_elevation.png
Levuka, Fiji_elevation.png
Florianópolis, Brazil_elevation.png
Darkhan, Mongolia_elevation.png
Kélo, Chad_elevation.png
Port-Gentil, Gabon_elevation.png
Sarande, Albania_elevation.png
San Miguelito, Panama_elevation.png
Bizerte, Tunisia_elevation.png
Galle, Sri Lanka_elevation.png
Moundou, Chad_elevation.png
Cayenne, French Guiana_elevation.png
Iloilo City, Philippines_elevation.png
Belgrade, Serbia_elevation.png
El Progreso, Honduras_elevation.png
Choibalsan, Mongolia_elevation.png
Varna, Bulgaria_elevation.png
Wad Madani, Sudan_elevation.png
Sheffield, United Kingdom_elevation.png
Antananarivo, Madagascar_elevation.png
Randers, Denmark_elevation.png
Sokodé, Togo_elevation.png
Medan, Indonesia_elevation.png
Hat Yai, Thailand_elevation.png
Wollongong, Australia_elevation.png
Chipata, Zambia_elevation.png
Chitre, Panama_elevation.png
Queluz, Portugal_elevation.png
Kuala Belait, Brunei_elevation.png
Kano, Nigeria_elevation.png
Lambarene, Gabon_elevation.png
Encarnación, Paraguay_elevation.png
Prijedor, Bosnia and Herzegovina_elevation.png
Tuzla, Bosnia and Herzegovina_elevation.png
Fes, Morocco_elevation.png
Dapaong, Togo_elevation.png
Elbasan, Albania_elevation.png
Tacna, Peru_elevation.png
Arequipa, Peru_elevation.png
Mostaganem, Algeria_elevation.png
San Lorenzo, Paraguay_elevation.png
David, Panama_elevation.png
Kranj, Slovenia_elevation.png
Rome, Italy_elevation.png
Evinayong, Equatorial Guinea_elevation.png
Vasteras, Sweden_elevation.png
Al Fashir, Sudan_elevation.png
Bairiki, Kiribati_elevation.png
Pedro Juan Caballero, Paraguay_elevation.png
Djougou, Benin_elevation.png
Liege, Belgium_elevation.png
Cardiff, United Kingdom_elevation.png
Ebolowa, Cameroon_elevation.png
Zamboanga City, Philippines_elevation.png
Bruges, Belgium_elevation.png
Owerri, Nigeria_elevation.png
Aveiro, Portugal_elevation.png
Sidon, Lebanon_elevation.png
Beersheba, Israel_elevation.png
Dosso, Niger_elevation.png
Cologne, Germany_elevation.png
Toluca, Mexico_elevation.png
Jonkoping, Sweden_elevation.png
Prilep, North Macedonia_elevation.png
Guayaquil, Ecuador_elevation.png
Tetovo, North Macedonia_elevation.png
Campinas, Brazil_elevation.png
Kassala, Sudan_elevation.png
Punakha, Bhutan_elevation.png
Córdoba, Argentina_elevation.png
Pacora, Panama_elevation.png
Esch-sur-Alzette, Luxembourg_elevation.png
Taipa, Macau_elevation.png
Bafoussam, Cameroon_elevation.png
Köniz, Switzerland_elevation.png
Maliana, Timor-Leste_elevation.png
Granada, Nicaragua_elevation.png
Porsgrunn, Norway_elevation.png
Guadalajara, Mexico_elevation.png
Taguig, Philippines_elevation.png
Hamilton, New Zealand_elevation.png
Bharatpur, Nepal_elevation.png
Kaédi, Mauritania_elevation.png
Bergen, Norway_elevation.png
Port Louis, Mauritius_elevation.png
Negombo, Sri Lanka_elevation.png
Szombathely, Hungary_elevation.png
Mekelle, Ethiopia_elevation.png
Augsburg, Germany_elevation.png
Gori, Georgia_elevation.png
San Miguel, El Salvador_elevation.png
Recife, Brazil_elevation.png
Dortmund, Germany_elevation.png
Kitale, Kenya_elevation.png
Potosi, Bolivia_elevation.png
Qom, Iran_elevation.png
Chingola, Zambia_elevation.png
Kandahar, Afghanistan_elevation.png
Nicosia, Cyprus_elevation.png
Alexandria, Egypt_elevation.png
Skien, Norway_elevation.png
Chillán, Chile_elevation.png
Mannheim, Germany_elevation.png
Antsirabe, Madagascar_elevation.png
Kingstown, Saint Vincent and the Grenadines_elevation.png
Tartu, Estonia_elevation.png
Viseu, Portugal_elevation.png
Macau, Macau_elevation.png
Odense, Denmark_elevation.png
Copenhagen, Denmark_elevation.png
Muharraq, Bahrain_elevation.png
San Jose, United States_elevation.png
Šibenik, Croatia_elevation.png
Grenoble, France_elevation.png
Toulon, France_elevation.png
Aswan, Egypt_elevation.png
Coimbatore, India_elevation.png
Bandar Seri Begawan, Brunei_elevation.png
Osorno, Chile_elevation.png
Dire Dawa, Ethiopia_elevation.png
Saskatoon, Canada_elevation.png
Thika, Kenya_elevation.png
Monrovia, Liberia_elevation.png
Kigali, Rwanda_elevation.png
Kitakyushu, Japan_elevation.png
Beni Mellal, Morocco_elevation.png
Quebec City, Canada_elevation.png
Luang Prabang, Laos_elevation.png
Telavi, Georgia_elevation.png
Nakuru, Kenya_elevation.png
Lambaré, Paraguay_elevation.png
Marondera, Zimbabwe_elevation.png
Daloa, Ivory Coast_elevation.png
Ostrava, Czech Republic_elevation.png
Siem Reap, Cambodia_elevation.png
Waterford, Ireland_elevation.png
Bratislava, Slovakia_elevation.png
Kolding, Denmark_elevation.png
San Antonio, United States_elevation.png
Malabo, Equatorial Guinea_elevation.png
Leon, Mexico_elevation.png
Rosario, Argentina_elevation.png
Surabaya, Indonesia_elevation.png
Bukhara, Uzbekistan_elevation.png
Tema, Ghana_elevation.png
Reggio Emilia, Italy_elevation.png
Tiraspol, Moldova_elevation.png
Los Angeles, United States_elevation.png
Xiamen, China_elevation.png
Suva, Fiji_elevation.png
Parnu, Estonia_elevation.png
Panjakent, Tajikistan_elevation.png
Enugu, Nigeria_elevation.png
Umm Salal, Qatar_elevation.png
Subotica, Serbia_elevation.png
Fort Portal, Uganda_elevation.png
Pokhara, Nepal_elevation.png
Agadir, Morocco_elevation.png
Douala, Cameroon_elevation.png
Oviedo, Spain_elevation.png
San Juan Sacatepéquez, Guatemala_elevation.png
Sunderland, United Kingdom_elevation.png
Santa Cruz de la Sierra, Bolivia_elevation.png
Mazar-e-Sharif, Afghanistan_elevation.png
Gabú, Guinea-Bissau_elevation.png
Winterthur, Switzerland_elevation.png
Culiacán, Mexico_elevation.png
Ciudad Delgado, El Salvador_elevation.png
Stara Zagora, Bulgaria_elevation.png
Banja Luka, Bosnia and Herzegovina_elevation.png
Pakse, Laos_elevation.png
Addis Ababa, Ethiopia_elevation.png
Pančevo, Serbia_elevation.png
Kenitra, Morocco_elevation.png
Paro, Bhutan_elevation.png
Zenica, Bosnia and Herzegovina_elevation.png
Santo Domingo, Ecuador_elevation.png
Atlanta, USA_elevation.png
Manchester, United Kingdom_elevation.png
Kampala, Uganda_elevation.png
Peja, Kosovo_elevation.png
Asunción, Paraguay_elevation.png
Kirkuk, Iraq_elevation.png
Rivera, Uruguay_elevation.png
Jizzakh, Uzbekistan_elevation.png
Koidu, Sierra Leone_elevation.png
Janakpur, Nepal_elevation.png
Assab, Eritrea_elevation.png
Nizwa, Oman_elevation.png
Hama, Syria_elevation.png
Goiânia, Brazil_elevation.png
Managua, Nicaragua_elevation.png
Sétif, Algeria_elevation.png
Anuradhapura, Sri Lanka_elevation.png
Vanadzor, Armenia_elevation.png
Danli, Honduras_elevation.png
Sarajevo, Bosnia and Herzegovina_elevation.png
Kinshasa, Democratic Republic of the Congo_elevation.png
Split, Croatia_elevation.png
Rotterdam, Netherlands_elevation.png
San Isidro, Costa Rica_elevation.png
Reading, United Kingdom_elevation.png
Zhengzhou, China_elevation.png
Birgunj, Nepal_elevation.png
Bossangoa, Central African Republic_elevation.png
Trujillo, Peru_elevation.png
Pune, India_elevation.png
Kabul, Afghanistan_elevation.png
Koper, Slovenia_elevation.png
Tamale, Ghana_elevation.png
Mecca, Saudi Arabia_elevation.png
Paysandu, Uruguay_elevation.png
Onverwacht, Suriname_elevation.png
Abeokuta, Nigeria_elevation.png
Xian, China_elevation.png
Iquique, Chile_elevation.png
Kukes, Albania_elevation.png
Karlsruhe, Germany_elevation.png
Kolkata, India_elevation.png
Ho Chi Minh City, Vietnam_elevation.png
Haarlem, Netherlands_elevation.png
Kuwait City, Kuwait_elevation.png
Constanta, Romania_elevation.png
Yaounde, Cameroon_elevation.png
Innsbruck, Austria_elevation.png
Nyiregyhaza, Hungary_elevation.png
Aktobe, Kazakhstan_elevation.png
Rundu, Namibia_elevation.png
Birmingham, United Kingdom_elevation.png
Abuja, Nigeria_elevation.png
Comilla, Bangladesh_elevation.png
Shubra El Kheima, Egypt_elevation.png
Faridabad, India_elevation.png
Kristiansand, Norway_elevation.png
Kampong Cham, Cambodia_elevation.png
Trnava, Slovakia_elevation.png
Thane, India_elevation.png
Mumbai, India_elevation.png
New Amsterdam, Guyana_elevation.png
Hlotse, Lesotho_elevation.png
Port Elizabeth, South Africa_elevation.png
Bologna, Italy_elevation.png
Houston, USA_elevation.png
Rakvere, Estonia_elevation.png
Mbale, Uganda_elevation.png
Nelson, New Zealand_elevation.png
Abu Dhabi, United Arab Emirates_elevation.png
Ambato, Ecuador_elevation.png
Jounieh, Lebanon_elevation.png
Niksic, Montenegro_elevation.png
Visakhapatnam, India_elevation.png
Skikda, Algeria_elevation.png
Ferizaj, Kosovo_elevation.png
Dallas, United States_elevation.png
Ljubljana, Slovenia_elevation.png
Sihanoukville, Cambodia_elevation.png
Huambo, Angola_elevation.png
Sumqayit, Azerbaijan_elevation.png
Muhanga, Rwanda_elevation.png
La Paz, Bolivia_elevation.png
Fier, Albania_elevation.png
Agra, India_elevation.png
Sunyani, Ghana_elevation.png
Orumiyeh, Iran_elevation.png
Tokmok, Kyrgyzstan_elevation.png
Juigalpa, Nicaragua_elevation.png
Wolverhampton, United Kingdom_elevation.png
Hiroshima, Japan_elevation.png
Limassol, Cyprus_elevation.png
Río Cuarto, Argentina_elevation.png
Varanasi, India_elevation.png
Calgary, Canada_elevation.png
Tripoli, Libya_elevation.png
Meknes, Morocco_elevation.png
Vantaa, Finland_elevation.png
Cape Coast, Ghana_elevation.png
Indore, India_elevation.png
Am Timan, Chad_elevation.png
Lucerne, Switzerland_elevation.png
Tutong, Brunei_elevation.png
Mixco, Guatemala_elevation.png
Ludhiana, India_elevation.png
Sumy, Ukraine_elevation.png
Gothenburg, Sweden_elevation.png
Korhogo, Ivory Coast_elevation.png
Mohale's Hoek, Lesotho_elevation.png
Aberdeen, United Kingdom_elevation.png
Cotonou, Benin_elevation.png
Lautoka, Fiji_elevation.png
Gavar, Armenia_elevation.png
Bogor, Indonesia_elevation.png
Santo Domingo, Dominican Republic_elevation.png

In [371]:
df

,country,city,elevation_file_name,description,tags
0,Lebanon,Beirut,"Beirut, Lebanon_elevation.png",The image shows a coastal region bordered by a...,"coast,ocean,mountain,hill,elevation,slope,upla..."
1,Pakistan,Peshawar,"Peshawar, Pakistan_elevation.png",The image displays a generally flat to gently ...,"plain,hill,river,stream,lowland,drainage,eleva..."
2,Denmark,Roskilde,"Roskilde, Denmark_elevation.png",The image displays a coastal terrain with a mi...,"coast,bay,river,estuary,island,peninsula,uplan..."
3,Guyana,Linden,"Linden, Guyana_elevation.png",The image shows a region dominated by low-lyin...,"river,plain,valley,tributary,basin,stream,hill..."
4,Azerbaijan,Ganja,"Ganja, Azerbaijan_elevation.png",The image depicts a landscape dominated by an ...,"valley,river,tributary,ridge,plateau,floodplai..."
...,...,...,...,...,...
1360,Australia,Newcastle,"Newcastle, Australia_elevation.png",The image shows a coastal area with a prominen...,"coast,river,ocean,inlet,estuary,floodplain,hil..."
1361,Canada,Hamilton,"Hamilton, Canada_elevation.png",The image shows a coastal region with a signif...,"coast,lake,hill,plateau,valley,river,stream,es..."
1362,Panama,Santiago,"Santiago, Panama_elevation.png",The image shows a mountainous inland region wi...,"mountain,valley,peak,ridge,canyon,highlands,st..."
1363,UK,Leeds,"Leeds, UK_elevation.png",The image depicts a rugged and hilly landscape...,"valley,river,ridge,hill,ravine,channel,highlan..."
1364,United Kingdom,London,"London, United Kingdom_elevation.png",The image shows a varied inland terrain charac...,"valley,river,upland,highlands,hill,tributary,r..."

In [372]:
df.to_csv(csv_path, index=False, quoting=csv.QUOTE_ALL)

In [373]:
import pandas as pd

# Load the datasets
new_metadata_path = '/home/salvador_cb/3_term/Applied_research_studio/data/csv/new_metadata.csv'
street_metadata_path = '/home/salvador_cb/3_term/Applied_research_studio/data/csv/street_metadata.csv'
overlap_metadata_path = '/home/salvador_cb/3_term/Applied_research_studio/data/csv/overlap_metadata.csv'

new_metadata = pd.read_csv(new_metadata_path)
street_metadata = pd.read_csv(street_metadata_path)
overlap_metadata = pd.read_csv(overlap_metadata_path)

# Merge the datasets on 'country' and 'city'
merged_df = pd.merge(new_metadata, street_metadata, on=['country', 'city'], how='inner')
merged_df = pd.merge(merged_df, overlap_metadata, on=['country', 'city'], how='inner')

# Reorder columns to match the desired structure
merged_df = merged_df[[
    "country", "city",
    "elevation_file_name", "elevation_description", "elevation_tags",
    "street_file_name", "street_description", "street_tags",
    "overlap_file_name", "overlap_description", "overlap_tags"
]]

In [374]:
merged_df

,country,city,elevation_file_name,elevation_description,elevation_tags,street_file_name,street_description,street_tags,overlap_file_name,overlap_description,overlap_tags
0,Lebanon,Beirut,"Beirut, Lebanon_elevation.png",The image shows a coastal region bordered by a...,"coast,ocean,mountain,hill,elevation,slope,upla...","Beirut, Lebanon_street_network.png",The image shows a largely dense urban area wit...,"dense, irregular, grid, main road, intersectio...","Beirut, Lebanon_overlap.png",The image depicts a varied urban street networ...,"grid, valley, elevation, winding, hillside, ar..."
1,Pakistan,Peshawar,"Peshawar, Pakistan_elevation.png",The image displays a generally flat to gently ...,"plain,hill,river,stream,lowland,drainage,eleva...","Peshawar, Pakistan_street_network.png",The image shows a highly varied street network...,"dense,grid,irregular,intersection,main road,hi...","Peshawar, Pakistan_overlap.png",The image presents an urban street network sup...,"valley, grid, elevation, winding, intersection..."
2,Denmark,Roskilde,"Roskilde, Denmark_elevation.png",The image displays a coastal terrain with a mi...,"coast,bay,river,estuary,island,peninsula,uplan...","Roskilde, Denmark_street_network.png",The image shows a central dense urban area wit...,"dense,irregular,grid,radial,main road,intersec...","Roskilde, Denmark_overlap.png",The image shows an urban street network intric...,"valley, grid, elevation, winding, intersection..."
3,Guyana,Linden,"Linden, Guyana_elevation.png",The image shows a region dominated by low-lyin...,"river,plain,valley,tributary,basin,stream,hill...","Linden, Guyana_street_network.png",The image shows a moderately dense urban stree...,"irregular,grid,cluster,intersection,main road,...","Linden, Guyana_overlap.png",The image shows a red urban street network ove...,"valley, grid, elevation, winding, intersection..."
4,Azerbaijan,Ganja,"Ganja, Azerbaijan_elevation.png",The image depicts a landscape dominated by an ...,"valley,river,tributary,ridge,plateau,floodplai...","Ganja, Azerbaijan_street_network.png",The image shows a dense urban area with a comb...,"grid,irregular,dense,sparse,main road,intersec...","Ganja, Azerbaijan_overlap.png",The image reveals a concentrated urban street ...,"valley, grid, elevation, winding, intersection..."
...,...,...,...,...,...,...,...,...,...,...,...
1360,Australia,Newcastle,"Newcastle, Australia_elevation.png",The image shows a coastal area with a prominen...,"coast,river,ocean,inlet,estuary,floodplain,hil...","Newcastle, Australia_street_network.png",The image shows a moderately dense urban area ...,"grid,irregular,dense,sparse,intersection,main ...","Newcastle, Australia_overlap.png",The image reveals an urban street network laid...,"valley, grid, elevation, winding, intersection..."
1361,Canada,Hamilton,"Hamilton, Canada_elevation.png",The image shows a coastal region with a signif...,"coast,lake,hill,plateau,valley,river,stream,es...","Hamilton, Canada_street_network.png",The image shows a varied urban area with a com...,"grid,dense,sparse,main road,intersection,clust...","Hamilton, Canada_overlap.png",The image depicts a striking interaction betwe...,"valley, grid, elevation, winding, intersection..."
1362,Panama,Santiago,"Santiago, Panama_elevation.png",The image shows a mountainous inland region wi...,"mountain,valley,peak,ridge,canyon,highlands,st...","Santiago, Panama_street_network.png",The image shows a moderately dense urban area ...,"grid,dense,irregular,main road,intersection,cl...","Santiago, Panama_overlap.png",The image shows a dense urban street network o...,"valley, grid, elevation, winding, intersection..."
1363,UK,Leeds,"Leeds, UK_elevation.png",The image depicts a rugged and hilly landscape...,"valley,river,ridge,hill,ravine,channel,highlan...","Leeds, UK_street_network.png",The image shows a densely built-up urban core ...,"dense,irregular,grid,radial,intersection,clust...","Leeds, UK_overlap.png",The image displays a complex urban street netw...,"valley, grid, elevation, winding, intersection..."
1364,United Kingdom,London,"London, United Kingdom_elevation.png",The image shows a varied inland terrain charac...,"valley,river,upland,highlands,hill,tributary,r...","London, United Kingdom_street_network.png",The image shows a dense urban area with a high...,"dense, irregular, radial, intersection, cluste...","London, United Kingdom_overlap.png",The image shows a strong correlation between t...,"valley, grid, elevation, winding, intersection..."

In [379]:
# Save the merged dataset to a new CSV file
output_path = '/home/salvador_cb/3_term/Applied_research_studio/data/csv/merged_metadata.csv'
merged_df.to_csv(output_path, index=False, quoting=csv.QUOTE_ALL)

print(f"Merged dataset saved to {output_path}")

Merged dataset saved to /home/salvador_cb/3_term/Applied_research_studio/data/csv/merged_metadata.csv

In [388]:
import pandas as pd
import csv

merged_df = pd.read_csv('/home/salvador_cb/3_term/Applied_research_studio/data/csv/merged_metadata.csv')

# Update file paths to include folder structure
merged_df['elevation_file_name'] = 'elevation/' + merged_df['elevation_file_name']
merged_df['street_file_name'] = 'street/' + merged_df['street_file_name']
merged_df['overlap_file_name'] = 'overlap/' + merged_df['overlap_file_name']

# Reorder columns to match the desired structure
merged_df = merged_df[[
    "country", "city",
    "elevation_file_name", "elevation_description", "elevation_tags",
    "street_file_name", "street_description", "street_tags",
    "overlap_file_name", "overlap_description", "overlap_tags"
]]

In [389]:
merged_df

,country,city,elevation_file_name,elevation_description,elevation_tags,street_file_name,street_description,street_tags,overlap_file_name,overlap_description,overlap_tags
0,Lebanon,Beirut,"elevation/Beirut, Lebanon_elevation.png",The image shows a coastal region bordered by a...,"coast,ocean,mountain,hill,elevation,slope,upla...","street/Beirut, Lebanon_street_network.png",The image shows a largely dense urban area wit...,"dense, irregular, grid, main road, intersectio...","overlap/Beirut, Lebanon_overlap.png",The image depicts a varied urban street networ...,"grid, valley, elevation, winding, hillside, ar..."
1,Pakistan,Peshawar,"elevation/Peshawar, Pakistan_elevation.png",The image displays a generally flat to gently ...,"plain,hill,river,stream,lowland,drainage,eleva...","street/Peshawar, Pakistan_street_network.png",The image shows a highly varied street network...,"dense,grid,irregular,intersection,main road,hi...","overlap/Peshawar, Pakistan_overlap.png",The image presents an urban street network sup...,"valley, grid, elevation, winding, intersection..."
2,Denmark,Roskilde,"elevation/Roskilde, Denmark_elevation.png",The image displays a coastal terrain with a mi...,"coast,bay,river,estuary,island,peninsula,uplan...","street/Roskilde, Denmark_street_network.png",The image shows a central dense urban area wit...,"dense,irregular,grid,radial,main road,intersec...","overlap/Roskilde, Denmark_overlap.png",The image shows an urban street network intric...,"valley, grid, elevation, winding, intersection..."
3,Guyana,Linden,"elevation/Linden, Guyana_elevation.png",The image shows a region dominated by low-lyin...,"river,plain,valley,tributary,basin,stream,hill...","street/Linden, Guyana_street_network.png",The image shows a moderately dense urban stree...,"irregular,grid,cluster,intersection,main road,...","overlap/Linden, Guyana_overlap.png",The image shows a red urban street network ove...,"valley, grid, elevation, winding, intersection..."
4,Azerbaijan,Ganja,"elevation/Ganja, Azerbaijan_elevation.png",The image depicts a landscape dominated by an ...,"valley,river,tributary,ridge,plateau,floodplai...","street/Ganja, Azerbaijan_street_network.png",The image shows a dense urban area with a comb...,"grid,irregular,dense,sparse,main road,intersec...","overlap/Ganja, Azerbaijan_overlap.png",The image reveals a concentrated urban street ...,"valley, grid, elevation, winding, intersection..."
...,...,...,...,...,...,...,...,...,...,...,...
1360,Australia,Newcastle,"elevation/Newcastle, Australia_elevation.png",The image shows a coastal area with a prominen...,"coast,river,ocean,inlet,estuary,floodplain,hil...","street/Newcastle, Australia_street_network.png",The image shows a moderately dense urban area ...,"grid,irregular,dense,sparse,intersection,main ...","overlap/Newcastle, Australia_overlap.png",The image reveals an urban street network laid...,"valley, grid, elevation, winding, intersection..."
1361,Canada,Hamilton,"elevation/Hamilton, Canada_elevation.png",The image shows a coastal region with a signif...,"coast,lake,hill,plateau,valley,river,stream,es...","street/Hamilton, Canada_street_network.png",The image shows a varied urban area with a com...,"grid,dense,sparse,main road,intersection,clust...","overlap/Hamilton, Canada_overlap.png",The image depicts a striking interaction betwe...,"valley, grid, elevation, winding, intersection..."
1362,Panama,Santiago,"elevation/Santiago, Panama_elevation.png",The image shows a mountainous inland region wi...,"mountain,valley,peak,ridge,canyon,highlands,st...","street/Santiago, Panama_street_network.png",The image shows a moderately dense urban area ...,"grid,dense,irregular,main road,intersection,cl...","overlap/Santiago, Panama_overlap.png",The image shows a dense urban street network o...,"valley, grid, elevation, winding, intersection..."
1363,UK,Leeds,"elevation/Leeds, UK_elevation.png",The image depicts a rugged and hilly landscape...,"valley,river,ridge,hill,ravine,channel,highlan...","street/Leeds, UK_street_network.png",The image shows a densely built-up urban core ...,"dense,irregular,grid,radial,intersection,clust...","overlap/Leeds, UK_overlap.png",The image displays a complex urban street netw...,"valley, grid, elevation, winding, intersection..."
1364,United Kingdom,London,"elevation/London, United Kingdom_elevation.png",The image shows a varied inland terrain charac...,"valley,river,upland,highlands,hill,tributary,r...","street/London, United Kingdom_street_network.png",The image shows a dense urban area with a high...,"dense, irregular, radial, intersection, cluste...","overlap/London, United Kingdom_overlap.png",The image shows a strong correlation between t...,"valley, grid, elevation, winding, intersection..."

In [390]:
# Save the merged dataset to a new CSV file
output_path = '/home/salvador_cb/3_term/Applied_research_studio/data/csv/new_merged_metadata.csv'
merged_df.to_csv(output_path, index=False, quoting=csv.QUOTE_ALL)

print(f"Merged dataset saved to {output_path}")

Merged dataset saved to /home/salvador_cb/3_term/Applied_research_studio/data/csv/new_merged_metadata.csv